feature: add mock auth api
bronfood-com/front pull request #21
Opened 2023-12-14 09:19 UTC by vitland

Добавил моковый апи, делал по принципу без эксепшенов, как я его понял. 
Возвращает только сообщение со статусом.

2023-12-24 16:25 UTC, vitland commented
Добавил интернационализацию на страницы регистрации и авторизации. 
Данные из полей ввода теперь собирает react-hook-form
В апи добавил запросы регистрации и выход

2023-12-25 12:04 UTC, cronon requested changes

2023-12-25 12:04 UTC, cronon commented on src/utils/api/auth.ts
> +interface RegisterData extends LoginData {
🤔 
я сначала хотел сказать так: код должен повторять бизнес-логику, и сущности в коде должны быть отражением бизнес-сущностей. То есть, мы когда говорим не с программистами, мы говорим "для регистрации нужно ввести номер, пароль, имя и галочку isOwner". Мы не говорим "нужно ввести те же данные, что и для логина, плюс имя и галочку". Поэтому так и пишем
```
interface RegisterData {
  phone: PhoneNumber,
  password: string,
  name: string,
  isOwner: boolean
}
```

А потом я задумался, может быть и плохо, что не говорим. Если мы будем говорить как во втором варианте, то мы никогда не забудем во время регистрацим. В таком случае лучше делать через композицию
```
interface RegisterData {
  loginData: LoginData,
  isOwner: boolean
}
```
однако это решение добавляет немножко сложности. А вероятность, что кто-то забудет прислать пароль во время регистрации я оцениваю в 0%. Посему решение не стоит того. Пускай будет первый вариант

2023-12-25 12:04 UTC, cronon commented on src/utils/api/auth.ts
> +    phone: string;
```suggestion
    phone: PhoneNumber;
```

2023-12-25 12:21 UTC, cronon commented on src/components/Popups/WithForm/SignUp/SignUp.tsx
кстати, таска-то была только страницу логина сделать. Тут уже сам смотри, как тебе удобнее будет, надо или доделать в этом ПРе, чтобы страница регистрации полностью работала, или можешь откатить изменения, и в этом ПРе доделать только страницу логина, а страницу регистрации - уже в другом

2023-12-26 13:24 UTC, vitland commented on src/components/Popups/WithForm/SignUp/SignUp.tsx
> +        if (res.errorMessage) return;
Поменял. Беков проинформировал. Будем договариваться по ключам.

2023-12-26 13:25 UTC, vitland commented on src/components/Popups/WithForm/SignUp/SignUp.tsx
Да, забыл перенести, исправил.

2023-12-26 13:25 UTC, vitland commented on src/components/Popups/WithForm/SignUp/SignUp.tsx
> +                    <Input type="text" name="input_username" placeholder={t('auth.namePlaceholder')} nameLabel={t('auth.nameInput')} register={register} errors={errors} pattern={regexClientName}></In
Исправил

2023-12-26 13:26 UTC, vitland commented on src/components/InputPhone/InputPhone.tsx
> +                {t('auth.phoneInput')}
Убрал переиспользование

2023-12-26 13:31 UTC, vitland commented on src/i18n.tsx
> +                        errorMessage: 'Телефон или пароль введен неверно, повторите попытку еще раз.',
Сделал немного по другому. Ключ передается текстом, так получается по проще передавать значение ```t(`signIn.${errorMessage}`)```

```
{
status: 'error', 
errorMessage: 'invalidCredentials'
}

```

2023-12-26 13:32 UTC, vitland commented on src/pages/SignIn/SignIn.tsx
> +        const res = await authApi.login({ phone: input_telephone, password: input_password });
Сделал

2023-12-26 13:34 UTC, vitland commented on src/pages/SignIn/SignIn.tsx
> +        alert(`status: ${res.status}, user: ${res.data?.name} ${res.data?.phone}`);
Добавил отображение ошибок

2023-12-26 16:18 UTC, vitland commented on src/utils/api/auth.ts
> +interface RegisterData extends LoginData {
Сделал первый вариант.

2023-12-26 16:19 UTC, vitland commented on src/utils/api/auth.ts
> +//TODO: custom type for phonenumber
Ок, учту. По формату договариваюсь с беком.

2023-12-27 12:44 UTC, cronon requested changes

2023-12-27 12:44 UTC, cronon commented on src/i18n.tsx
> +                        invalidPhoneNumber: 'Телефон уже используется.',
```suggestion
                        phoneNumberIsAlreadyUsed: 'Телефон уже используется.',
```

2023-12-27 12:44 UTC, cronon commented on src/i18n.tsx
> +                        errorMessage: 'Неверный ввод',
```suggestion
                        invalidPhoneNumberFormat: 'Неверный ввод',
```

2023-12-27 12:44 UTC, cronon commented on src/pages/SignIn/SignIn.tsx
> +        navigate('/');
```suggestion
        } else {
          navigate('/');
        }  
```
с else это немножко более явно. Смотришь на navigate и сразу видишь, что он не всегда происходит. А без else смотришь на navigate и надо еще наверх посмотреть не затесался ли там return

2023-12-27 12:44 UTC, cronon commented on src/pages/SignUp/SignUp.tsx
> +        navigate('/signup_done');
```suggestion
        } else {
          navigate('/');
        }  
```

2023-12-27 12:44 UTC, cronon commented on src/pages/SignIn/SignIn.tsx
> +        const res = await authApi.login({ phone: phoneNumber, password });
```suggestion
        setErrorMessage(null); 
        const res = await authApi.login({ phone: phoneNumber, password });
```
чтобы юзер понимал, что что-то происходит
А еще по-хорошему нужно как-то показывать, что форма загружается. это следующим шагом сделаем https://github.com/orgs/bronfood-com/projects/1/views/1?pane=issue&itemId=48512877

2023-12-27 12:44 UTC, cronon commented on src/pages/SignIn/SignIn.tsx
> +    const [errorMessage, setErrorMessage] = useState<string | undefined>('')
```suggestion
    const [errorMessage, setErrorMessage] = useState<string | null>(null)
```
1 errorMessage и showError ты дальше меняешь только одновременно. Это ясный симптом, что один из них настоящий стейт, который мы меняем. А второй - может быть вычислен из первого. Из true или false получить целую строку невозможно, А из строки с ошибкой сделать true или false можно. Поэтому errorMessage остается как стейт, а showError будем выводить из наличия или отсутствия errorMessage
```
const showError =  !!errorMessage // то есть errorMessage ? true : false;
```
число стейтов надо держать минимальным. А если ты видишь, что два стейта как-то между собой связаны, то надо подумать как вывести один из другого. Упражнение стоит того, сильно упрощает код, и убирает необходимость строго следить чтобы эти стейты всегда были синхронизированы.

2 Если я сделаю showError = true, а setMessage = undefined. То это будет нонсенс. Структуры данных должны по максимуму быть такими, чтобы невозможные с точки бизнес-логики состояния было невозможно сделать в коде. Тогда код не даст тебе наступить на грабли, а свой ресурс внимания ты сможешь потратить на дальнейшие победы

3 Про null | string. В первую очередь так принято для ситуаций "значение или нет значения". Я это так объясняю, что когда ты видишь null, то понимаешь, что его сознательно кто-то поставил. А когда undefined - то непонятно или сознательно поставил или просто забыл что-то

2023-12-27 12:44 UTC, cronon commented on src/pages/SignUp/SignUp.tsx
> +    const [errorMessage, setErrorMessage] = useState<string | undefined>('');
```suggestion
    const [errorMessage, setErrorMessage] = useState<string | null>(null);
```

2023-12-27 14:21 UTC, olgaAsmith commented on src/i18n.tsx
> +                        invalidPhoneNumber: 'Телефон уже используется.',
может быть уточнить "номер телефона..."

2023-12-27 18:12 UTC, vitland commented on src/i18n.tsx
> +                        invalidPhoneNumber: 'Телефон уже используется.',
Ага, поменял

2023-12-27 18:13 UTC, vitland commented on src/i18n.tsx
> +                        errorMessage: 'Неверный ввод',
Поменял

2023-12-27 18:15 UTC, vitland commented on src/pages/SignUp/SignUp.tsx
> +        navigate('/signup_done');
Поменял

2023-12-27 18:43 UTC, vitland commented on src/pages/SignIn/SignIn.tsx
> +        const res = await authApi.login({ phone: phoneNumber, password });
Добавил сброс ошибки

2023-12-27 18:43 UTC, vitland commented on src/pages/SignIn/SignIn.tsx
> +    const [errorMessage, setErrorMessage] = useState<string | undefined>('')
Поменял

2023-12-27 18:43 UTC, vitland commented on src/pages/SignUp/SignUp.tsx
> +    const [errorMessage, setErrorMessage] = useState<string | undefined>('');
Поменял

2023-12-28 11:47 UTC, cronon commented on src/i18n.tsx
> +                    },
надо, чтобы структура объектов здесь повторяла пути в файлах. То есть чтобы ключи были components.inputPhone и pages.signUp pages.signIn
так, чтобы из ключа можно было легко понять где он применяется. Когда будем переводить на казахский, то это облегчит нам жизнь - поменял ключи в файле и сразу открываешь нужное место в приложении, чтобы проверить как оно работает

2023-12-28 13:13 UTC, vitland commented on src/i18n.tsx
> +                    },
Поменял

2023-12-28 13:20 UTC, cronon approved these changes

2023-12-28 13:26 UTC, merged