Feature/input hide password
bronfood-com/front pull request #27
Opened 2023-12-29 21:46 UTC by vitland

Добавил тоггл видимости пароля. Есть баг с иконкой, почему-то не вытаскивается из фигмы в нормальном виде. 
![image](https://github.com/bronfood-com/front/assets/25207136/9769a37a-26ef-421c-9117-8adb5ccebb15)

2024-01-09 12:59 UTC, cronon requested changes
Ну если есть баг с иконкой, то надо фиксить. А пока не пофикшен лучше не создавать ПР. Потому, что может быть такое, что чтобы пофиксить баг надо будет половину кода переписать, и получится, что ревьюверы зря смотрели твой текущий код.

Еще так делают: ПР назвать WIP Feature/input hide password. WIP - это work in progress. Пока висит WIP на ПРе, то люди не считают себя обязанными его проверять и такой ПР нельзя мержить. А когда все готово, тогда убирают WIP.

Вот, такая возможность есть, но я предпочитаю ее не юзать, потому, что WIP ПРов становится много и в них теряются уже готовые ПРы

2024-01-09 12:59 UTC, cronon commented on src/components/Input/Input.tsx
> +    togglePasswordVisability?: () => void;
```suggestion
    togglePasswordVisibility?: () => void;
```

2024-01-09 12:59 UTC, cronon commented on src/components/Input/Input.tsx
> +    const renderPasswordVisabilityIcon = () => (props.name === 'password' ? props.type === 'password' ? <HidePasswordIcon className={styles.input__hideIcon} onClick={props.togglePasswordVisability} /
```suggestion
    const visibilityIcon = (props.name === 'password' ? props.type === 'password' ? <HidePasswordIcon className={styles.input__hideIcon} onClick={props.togglePasswordVisability} /> : <ShowPasswordIcon className={styles.input__hideIcon} onClick={props.togglePasswordVisability} /> : null);
```
и там ниже
```
{visibilityIcon}
```
то есть, это можно сделать без функции, и без функции будет несколько проще, поэтому стоит делать без функции.

А вообще лучше сделать отдельный компонент PasswordInput который будет в себе это поведение прятать, и в месте его использования не надо будет заводить стейт isPasswordVisible

2024-01-12 09:48 UTC, vitland commented
Пофиксли баг с иконкой. Поле пароля вынес в отдельный компонент.

2024-01-12 14:20 UTC, cronon approved these changes

2024-01-12 18:17 UTC, merged