add popup bg
bronfood-com/front pull request #33
Opened 2024-01-11 13:41 UTC by olgaAsmith

add bg popup
add menu above all, map under menu
fix margin

2024-01-11 16:58 UTC, cronon requested changes

2024-01-11 16:58 UTC, cronon commented on vite.config.ts
> +    //base: '/front/',
?

2024-01-11 16:58 UTC, cronon commented on src/components/Header/Header.module.scss
> +    z-index: 999;
чтобы не терять z-indexы в разных компонентах, заведи плз глобальную scss мапу вида
```
zIndexes = {
  header: 999
}
```
И в дальнейшем z-indexы брать только из нее

2024-01-11 16:58 UTC, cronon commented on src/components/Popups/Popup/Popup.module.scss
> +    &_background {
обычно это называется overlay. Он есть не на каждой странице. Например, его нет на странице входа и регистрации. Но есть вокруг попапа "Вы действительно хотите выйти"
![image](https://github.com/bronfood-com/front/assets/4602009/fc985d70-3d4b-4631-9f85-2457ab342d55)

2024-01-11 17:01 UTC, cronon commented on src/components/Input/Input.tsx
> +    validate?: (value: FieldValues) => string | boolean;
Получается что у нас преттиер не работал раньше? Надо всем теперь проверить, чтобы работал

Лучше косметические изменения делать в отдельном ПРе, теперь будет тяжело мержить

2024-01-11 18:48 UTC, olgaAsmith commented on src/components/Input/Input.tsx
> +    validate?: (value: FieldValues) => string | boolean;
на npm run, авто нет. вручную надо прогонять

2024-01-12 14:18 UTC, cronon commented on src/components/Input/Input.tsx
> +    validate?: (value: FieldValues) => string | boolean;
можно как-то настроить вс код, чтобы он так делал. Еще делают преттиер в прекоммит хуках

я сделал тикет https://github.com/orgs/bronfood-com/projects/1/views/1?pane=issue&itemId=49819223

2024-01-12 14:57 UTC, olgaAsmith commented on src/components/Header/Header.module.scss
> +    z-index: 999;
Это как то так?:

$zIndexes: (
    header: 999
)
.......
z-index: map-get($zIndexes, header);

2024-01-12 15:13 UTC, cronon commented on src/components/Header/Header.module.scss
> +    z-index: 999;
да

2024-01-12 16:32 UTC, olgaAsmith commented on vite.config.ts
> +    //base: '/front/',
--->> base: process.env.NODE_ENV === 'production' ? '/front/' : ''

2024-01-15 13:26 UTC, cronon approved these changes

2024-01-15 13:28 UTC, cronon approved these changes

2024-01-15 15:03 UTC, merged