Feature/user api
bronfood-com/front pull request #36
Opened 2024-01-16 16:33 UTC by vitland

Новый апи.
Функционал смены пароля

2024-01-18 17:27 UTC, cronon requested changes

2024-01-18 17:27 UTC, cronon commented on src/utils/api/user.ts
> +}
это должны быть те же самые типы, что и в auth.ts 
лучше просто добавить editPassoword к классу AuthApi

2024-01-18 17:51 UTC, cronon commented on src/pages/NewPassword/NewPassword.tsx
> +            navigate('/password_done');
🤔 Пускай в этом ПРе остается так. Теперь я думаю, что некруто когда можно просто открыть bronfood.com/password_done  и тебе вдруг говорится, что твой пароль изменен. 

я сделал отдельный тикет https://github.com/orgs/bronfood-com/projects/1?pane=issue&itemId=50432311

2024-01-27 13:01 UTC, vitland commented on src/utils/api/user.ts
> +}
поправил

2024-01-29 14:18 UTC, cronon approved these changes

2024-01-29 14:18 UTC, cronon commented on src/utils/api/auth.ts
> +            return { status: 'success', data: { name: 'User', phone: '+7 999 99 99 99', isOwner: false } };
```suggestion
            return { status: 'success', data: { name: 'User', phone: '+7 999 999 99 99', isOwner: false } };
```

вы с бэками договрились про номера телефонов, можно ли с ними делать пробелы или скобочки?

2024-02-01 17:58 UTC, merged