fix bag delete пробел
bronfood-com/front pull request #37
Opened 2024-01-16 18:04 UTC by RomanAnurov

В ПР #35  забыл убрать пробел не нужный и он улетел в  main /

2024-01-16 18:25 UTC, RomanAnurov commented on package-lock.json
Не понял а почему в package-lock.json ключи переписались я что-то устаревшее запулил или как эт получилось?

2024-01-16 18:30 UTC, RomanAnurov reviewed
?

2024-01-16 19:13 UTC, RomanAnurov commented
Вернул маску номера как была ранее   mask="+7 (999) 99-99-99"    
Так сделано на макете и видимо это для Казахстанских номеров так сказала @olgaAsmith

2024-01-18 14:42 UTC, olgaAsmith approved these changes

2024-01-18 17:22 UTC, cronon requested changes

2024-01-18 17:22 UTC, cronon commented on src/components/InputPhone/InputPhone.tsx
> +                mask="+7 (999) 99-99-99"
![image](https://github.com/bronfood-com/front/assets/4602009/914eea4d-8602-4bfe-93bb-8cb191472ef7)
Всего 11 цифр, как и в России

2024-01-18 17:22 UTC, cronon commented on package-lock.json
надо откатить твои изменения в package-lock

2024-01-18 21:00 UTC, RomanAnurov commented on src/components/InputPhone/InputPhone.tsx
> +                mask="+7 (999) 99-99-99"
Понятно номер как и в России, но ранее сделали по фигме

2024-01-18 21:02 UTC, RomanAnurov commented on package-lock.json
хорошо

2024-01-19 09:41 UTC, cronon approved these changes

2024-01-19 10:13 UTC, merged