add infopopup
bronfood-com/front pull request #41
Opened 2024-01-23 19:16 UTC by olgaAsmith

Открывает информационное окно после регистрации, через пропсы

2024-01-24 13:07 UTC, cronon requested changes

2024-01-24 13:07 UTC, cronon commented on src/components/Popups/InfoPopup/InfoPopup.tsx
> +    openInfoPopup: () => void;
судя по докам должно быть `closeInfoPopup`

2024-01-24 13:07 UTC, cronon commented on src/components/Popups/InfoPopup/PopupSignupSuccess/PopupSignupSuccess.tsx
> +    openInfoPopup: () => void;
судя по докам должно быть `closeInfoPopup`

2024-01-24 13:07 UTC, cronon commented on src/components/Popups/InfoPopup/PopupSignupSuccess/PopupSignupSuccess.tsx
так как он появляется только на странице регистрации, то положи его пожалуйста в папку со страницей регистрации

2024-01-24 13:07 UTC, cronon commented on src/App.tsx
> +    }, [isInfoPopupOpened]);
логика открытия и закрытия попапа успеха регистрации должна лежать на странице регистрации. Если ты хочешь рендерить его выше по дереву, чем весь остальной дом, то можно использовать Portals

2024-01-24 21:39 UTC, olgaAsmith commented on src/components/Popups/InfoPopup/InfoPopup.tsx
> +    openInfoPopup: () => void;
делаю handle из signup

2024-01-24 21:39 UTC, olgaAsmith commented on src/components/Popups/InfoPopup/PopupSignupSuccess/PopupSignupSuccess.tsx
> +    openInfoPopup: () => void;
делаю handle из signup

2024-01-24 21:39 UTC, olgaAsmith commented on src/components/Popups/InfoPopup/PopupSignupSuccess/PopupSignupSuccess.tsx
++

2024-01-24 21:39 UTC, olgaAsmith commented on src/App.tsx
> +    }, [isInfoPopupOpened]);
я думала может объединить эти инфо окна, там потом их больше будет. 
--> отправиа open/close в signup

2024-01-25 09:30 UTC, cronon commented on src/components/Popups/InfoPopup/InfoPopup.tsx
> +    handleInfoPopup: (value: boolean) => void;
Он вызывается только с false. Более того, нет смысла вызывать его с true изнутри попапа. Пользователь когда решает показать этот попап, он понимает в какой момент это происходит и ему нет нужды дополнительно изучать апи попапа чтобы выловить этот момент. Допустим задача показать попап и начать загрузку

```
<button onClick={() => { setIsOpened(true); startLoading() } />
<InfoPopup isOpened={isOpened}/>
vs
<button onClick={() => { setIsOpened(true); } />
<InfoPopup isOpened={isOpened} handleInfoPopup={open =>{ if (open) { startLoading()} }}/> {/* код делает тоже самое, что и в первом случае, только разнесен по разным местам, плюс надо еще напрячься чтобы прочитать доку к handleInfoPopup. */}
```
Поэтому можно апи упростить и оставить `onClose: () => void`

2024-01-25 09:30 UTC, cronon commented on src/App.tsx
> +    }, [isInfoPopupOpened]);
что ты имеешь в виду под объединить?

2024-01-25 11:10 UTC, olgaAsmith commented on src/components/Popups/InfoPopup/InfoPopup.tsx
> +    handleInfoPopup: (value: boolean) => void;
но он же говорит об успешности регистрации. а так он откроется поверх регистрации, и сразу по клику.

2024-01-25 11:10 UTC, olgaAsmith commented on src/App.tsx
> +    }, [isInfoPopupOpened]);
в одну функцию

2024-01-25 14:22 UTC, cronon commented on src/App.tsx
> +    }, [isInfoPopupOpened]);
зачем?

2024-01-25 14:24 UTC, cronon commented on src/components/Popups/InfoPopup/InfoPopup.tsx
> +    handleInfoPopup: (value: boolean) => void;
Компонент InfoPopup не должен ничего знать про успешную регистрацию, внутри себя он только понимает, что пришло время закрыться и он сообщает об этом наружу

2024-01-25 15:45 UTC, olgaAsmith commented on src/components/Popups/InfoPopup/InfoPopup.tsx
> +    handleInfoPopup: (value: boolean) => void;
конкретно этому компоненту прописать отдельно функцию на закрытие

2024-01-25 16:36 UTC, cronon commented on src/components/Popups/InfoPopup/InfoPopup.tsx
> +    handleInfoPopup: (value: boolean) => void;
я тебя не понимаю
в каких случаях ты хочешь вызывать props.handleInfoPopup(true) и в каких случаях ты будешь передавать в попап функцию которая будет смотреть закрылся попап или открылся? `<InfoPopup handleInfoPopup={open =>{ if (open) { doSomething() } else { doAnotherThing() } }}`

2024-01-25 16:38 UTC, cronon commented on src/App.tsx
> +    }, [isInfoPopupOpened]);
напиши плз схематично как ты предполагаешь будут выглядеть оба решения: с одной функцией на уровне App и с  отдельными функциями каждая в своем комопненте

2024-01-26 14:59 UTC, cronon requested changes

2024-01-26 14:59 UTC, cronon commented on src/pages/SignUp/PopupSignupSuccess/PopupSignupSuccess.tsx
> +    closeInfoPopup: () => void;
Здесь и в InfoPopup

```suggestion
    /**
     * Fires when info popup closes
     */
    onCloseInfoPopup: () => void;
```
эвент хэндлеры в пропсах начинаются на on. Как например, onClick, onKeypress. А в доке пишут когда этот хэндлер вызывается.

2024-01-26 20:15 UTC, olgaAsmith commented on src/pages/SignUp/PopupSignupSuccess/PopupSignupSuccess.tsx
> +    closeInfoPopup: () => void;
Хорошо. Только можно fires на works?

2024-01-27 09:06 UTC, cronon commented on src/pages/SignUp/PopupSignupSuccess/PopupSignupSuccess.tsx
> +    closeInfoPopup: () => void;
works я бы понял как то, что оно вызывается много раз в течение жизни. Про эвенты, колбэки обычно пишут fires, triggered, is called

2024-01-27 11:44 UTC, olgaAsmith commented on src/pages/SignUp/PopupSignupSuccess/PopupSignupSuccess.tsx
> +    closeInfoPopup: () => void;
хорошо, пусть стреляет

2024-01-29 14:14 UTC, cronon approved these changes

2024-01-29 17:04 UTC, merged