fix: component Preloader
bronfood-com/front pull request #42
Opened 2024-01-23 21:37 UTC by RomanAnurov

Компонент Preloader/ Пока никуда его не встраива в этом ПР 

https://github.com/bronfood-com/front/assets/99470278/e04650c8-06cd-45ef-b3a7-f10a05f7f701

2024-01-25 16:54 UTC, RomanAnurov commented
Понял уже делаю

2024-01-28 21:05 UTC, RomanAnurov commented
Встроил в компонент регистрации прелодер

https://github.com/bronfood-com/front/assets/99470278/817ed739-1bc6-4c3a-bfc4-f544fb87ca2a

2024-01-29 14:24 UTC, cronon requested changes

2024-01-29 14:24 UTC, cronon commented on src/pages/SignUp/SignUp.tsx
>                      <div className={styles.form__warning}></div>
нужно делать все инпуты и кнопки disabled на время загрузки

2024-01-29 14:24 UTC, cronon commented on src/components/Preloader/Preloader.tsx
> +    text?: string;
так как текст не используется, то надо эту проперти убрать, соответственно и из 17 строчки и из css

2024-01-29 15:46 UTC, RomanAnurov commented on src/components/Preloader/Preloader.tsx
> +    text?: string;
ок

2024-01-29 15:46 UTC, RomanAnurov commented on src/pages/SignUp/SignUp.tsx
>                      <div className={styles.form__warning}></div>
ну так то да

2024-01-29 23:07 UTC, RomanAnurov commented on src/pages/SignUp/SignUp.tsx
>                      <div className={styles.form__warning}></div>
Инпуты обернул <fieldset disabled={isLoading}>
И в компонент кнопки добавил пропс  disabled
                <Button disabled={isLoading}>

2024-01-30 10:00 UTC, cronon requested changes

2024-01-30 10:00 UTC, cronon commented on src/pages/SignUp/PopupSignupSuccess/PopupSignupSuccess.tsx
> -        <InfoPopup isOpened={props.isOpened} onCloseInfoPopup={props.onCloseInfoPopup}>
нужно вернуть как было, теперь такие попапы не имеют своего урла, а открываются только как часть страницы, которая их вызывает
https://github.com/orgs/bronfood-com/projects/1/views/1?pane=issue&itemId=50432311

2024-01-31 10:22 UTC, cronon approved these changes
не забудь плз про формы входа и смены пароля. Можно вместе сделать, можно по-отдельности. Но этот ПР конечно лучше смержить, вычеркнуть один айтем из списка дел и вздохнуть свободно

2024-01-31 10:33 UTC, RomanAnurov commented
Тогда смёржу, а остальное сделаю вечером. Вход и смену пароля.

2024-01-31 10:33 UTC, merged