Feature/user context
bronfood-com/front pull request #43
Opened 2024-01-27 08:37 UTC by vitland

Добавил контекст юзера.
Запросы к апи перенесены в контекст.
При авторизации пользователь добавляется в локал стор.

2024-01-29 14:44 UTC, cronon requested changes

2024-01-29 14:44 UTC, cronon commented on src/App.tsx
> +// import { useEffect, useState } from 'react';
закомменченный код надо удалять, иначе он останется навечно

2024-01-29 14:44 UTC, cronon commented on src/App.tsx
> +            <Header isLogin={!!currentUser} />
стоит тогда добавить `const isLogin = !!currentUser; return {isLogin, ... }` в хук. так как эта функциональность используется везде

2024-01-29 14:44 UTC, cronon commented on src/contexts/CurrentUserContext.tsx
> +    currentUser: User | null | undefined;
откуда появился undefined? Везде, где можно, надо его избегать. Обычно когда видишь null, то понимаешь, что другой человек имел в виду отстутствие чего-то. А когда видишь undefined, то подозреваешь, что что-то забыли. Оставь только null плз

2024-01-29 14:44 UTC, cronon commented on src/contexts/CurrentUserContext.tsx
> +            console.log('first');
console.log надо убирать, по идее еслинт должен на него ругаться

Еще еслинт должен ругаться на то, что setErrorMessage и остальные не переданы как зависимости.
Сиай похоже не сработал потому, что мерж-конфликты есть. Надо после открытия ПРа его еще раз посмотреть. Тогда можно найти вещи, оставленные в коде по невнимательности. Плюс, надо убедится, что ПР готов к мержу, и тогда имеет смысл его ревьювать. 

Иначе может быть такое, что чтобы пофиксить билд и мерж-конфликты, надо будет много чего поменять, и тогда получится что ревью надо будет делать заново.

2024-01-29 14:44 UTC, cronon commented on src/contexts/CurrentUserContext.tsx
> +    const { getItem, setItem, removeItem } = useLocalStorage();
а в чем разница между хуком и просто использованием localStorage.getItem ?

кмк это я не в первый раз такое вижу, это на курсах где-то дают хук с localStorage?

2024-01-29 14:44 UTC, cronon commented on src/contexts/CurrentUserContext.tsx
> +    const signUp = useCallback(async (data: FieldValues) => {
похоже что эта функция нигде не используется

2024-01-30 20:54 UTC, vitland commented on src/App.tsx
> +// import { useEffect, useState } from 'react';
убрал

2024-01-30 20:54 UTC, vitland commented on src/App.tsx
> +            <Header isLogin={!!currentUser} />
добавил

2024-01-30 21:15 UTC, vitland commented on src/contexts/CurrentUserContext.tsx
> +    currentUser: User | null | undefined;
undefined появился, из-за типов в апи. 

```async register({ name, phone, password }: RegisterData): Promise<{ status: 'success' | 'error'; data?: User; errorMessage?: string }> {}```

Поменял.

2024-02-01 17:23 UTC, vitland commented on src/contexts/CurrentUserContext.tsx
> +            console.log('first');
Взял изменения из мейна, все проверки прошли.

2024-02-01 17:34 UTC, vitland commented on src/contexts/CurrentUserContext.tsx
> +    const { getItem, setItem, removeItem } = useLocalStorage();
Нашел в интернете пример. Хотел все раскидать на отдельные хуки, но передумал. Сейчас убрал его.

2024-02-01 17:34 UTC, vitland commented on src/contexts/CurrentUserContext.tsx
> +    const signUp = useCallback(async (data: FieldValues) => {
Добавил использование

2024-02-02 15:33 UTC, cronon requested changes

2024-02-02 15:33 UTC, cronon commented on src/pages/SignIn/SignIn.tsx
>      };
Захожу на страницу входа, пишу телефон и пароль, нажимаю Войти. Показывает попап успеха, через некоторое время он закрывается, и меня перенаправляет на главную /. Я открываю меню и в меню вижу пункты "Выйти", "Редактировать личные данные" и "Редактировать банковские данные". Все как надо. Нажимаю на Редактировать личные данные, переходит на /profile. А потом редиректит на главную /, и как будто я разлогинен. Из localstorage юзер исчезает

То же самое происходит и если начать со страницы регистрации

2024-02-02 15:33 UTC, cronon commented on src/contexts/CurrentUserContext.tsx
> +    const signUp = async (data: FieldValues) => {
я зарегался, мне показывает пункты меню как будто я зашел. Потом я опять открываю урл https://bronfood-com.github.io/front/pr-preview/pr-43/ и мне показывает как будто я не зашел. В LocalStorage нет юзера

2024-02-02 15:33 UTC, cronon commented on src/utils/api/auth.ts
> +            return { status: 'success', data: { name: 'User', phone: '7999999999', isOwner: false } };
напиши плз jsdoc к типу PhoneNumber что это цифры без ничего

2024-02-02 15:33 UTC, cronon commented on src/pages/SignIn/SignIn.tsx
>      };
Добавь пожалуйста тикет в туду колонку чтобы убрать ссылку "Редактировать банковские данные". Кто будет делать эту страницу никак не сможет забыть о том, чтобы добавить эту ссылку. Но если мы не будем делать эту страницу, то мы легко забудем, что у нас есть ссылка которая никуда не ведет.
На текущий момент еще непонятно как будет работа с карточками происходить

2024-02-03 10:08 UTC, vitland commented on src/pages/SignIn/SignIn.tsx
>      };
Пофиксил баг с логаутом. Все компоненты перевел на контекст, убрал прос дриллинг.

2024-02-03 10:10 UTC, vitland commented on src/contexts/CurrentUserContext.tsx
> +    const signUp = async (data: FieldValues) => {
Исправил

2024-02-03 10:10 UTC, vitland commented on src/utils/api/auth.ts
> +            return { status: 'success', data: { name: 'User', phone: '7999999999', isOwner: false } };
Написал

2024-02-05 10:03 UTC, cronon commented on src/pages/SignIn/SignIn.tsx
> +        // eslint-disable-next-line react-hooks/exhaustive-deps
Надо написать строчкой выше почему это правило отключается. Для всех мест оно подходит, а для этого места не подходит. То есть в этом месте происходит что-то необычное, и это надо описать.

2024-02-05 10:04 UTC, cronon commented on src/utils/api/auth.ts
> + 10 digits sting, no space, brackets, or +
```suggestion
 10 digits string, no space, brackets, or +
```

2024-02-05 10:08 UTC, cronon commented on src/pages/SignIn/SignIn.tsx
> +        // eslint-disable-next-line react-hooks/exhaustive-deps
Подозреваю, что он хотел, чтобы navigate тоже тут был. Это приводило к чему-то плохому? Если все работало, то надо оставить navigate

2024-02-05 10:11 UTC, cronon commented on src/contexts/CurrentUserContext.tsx
> +    }, []);
я удивился, что оно не просит setState поместить сюда, оказывается они сделали, чтобы не надо было этого делать.
https://legacy.reactjs.org/docs/hooks-reference.html#usestate
"it’s safe to omit from the useEffect or useCallback dependency list." 
А раньше была морока

2024-02-07 17:25 UTC, vitland commented on src/utils/api/auth.ts
> + 10 digits sting, no space, brackets, or +
исправил

2024-02-07 18:38 UTC, cronon approved these changes

2024-02-07 18:40 UTC, merged