fix: Preloader SignIn PasswordRecavery NewPassword
bronfood-com/front pull request #48
Opened 2024-01-31 19:58 UTC by RomanAnurov

В этом таске Preloader  встроен в Компоненты SignIn(вход), В логику смены пароля, которая состоит из 2-х шагов PasswordRecovery и NewPassword.

2024-02-01 08:57 UTC, cronon requested changes

2024-02-01 08:57 UTC, cronon commented on src/pages/NewPassword/NewPassword.tsx
> +        setIsLoading(false);
но ведь это происходит синхронно за 10мс, как увидеть лоадер? Надо сейчас убрать, и добавить тогда, когда будет здесь запрос к серверу.
Добавь пожалуйста к таске про восстановление пароля, что нужно добавить лоадер. И сделай еще таску "добавить моковый апи для страницы NewPassword"

2024-02-01 09:11 UTC, RomanAnurov commented on src/pages/NewPassword/NewPassword.tsx
> +        setIsLoading(false);
Ты сам говорил что нужно делать короткие и простые таски. Я тут добавил лоадер. Можно это смёржить. А про моковый запрос для восстановления пароля сделать новый таск.

2024-02-01 09:13 UTC, RomanAnurov commented on src/pages/NewPassword/NewPassword.tsx
> +        setIsLoading(false);
Или ты предлагаешь всё что связано с лоадером удалить из этих 2-х компонентов для восстановления пароля

2024-02-01 09:15 UTC, RomanAnurov commented on src/pages/NewPassword/NewPassword.tsx
> +        setIsLoading(false);
> но ведь это происходит синхронно за 10мс, как увидеть лоадер? Надо сейчас убрать, и добавить тогда, когда будет здесь запрос к серверу. Добавь пожалуйста к таске про восстановление пароля, что нужно добавить лоадер. И сделай еще таску "добавить моковый апи для страницы NewPassword"
Ты сам говорил что нужно делать короткие и простые таски. Я тут добавил лоадер. Можно это смёржить. А про моковый запрос для восстановления пароля сделать новый таск

2024-02-01 09:17 UTC, RomanAnurov commented on src/pages/NewPassword/NewPassword.tsx
> +        setIsLoading(false);
И тут два экрана смены пароля. PasswordRecavery и New Password

2024-02-06 12:57 UTC, cronon commented on src/components/Popups/InfoPopup/InfoPopup.tsx
> +    }, [navigate]);
нужно избегать лишний изменений, я подозреваю, у тебя из-за этого мерж-конфликт сейчас

2024-02-06 13:04 UTC, cronon commented on src/pages/NewPassword/NewPassword.tsx
> +        setIsLoading(false);
прикрепи сюда пожалуйста ссылки на тикеты, которые ты создал

2024-02-06 13:04 UTC, cronon approved these changes

2024-02-06 16:21 UTC, RomanAnurov commented on src/pages/NewPassword/NewPassword.tsx
> +        setIsLoading(false);
@cronon Какие ты имеешь в виду тикеты? Все с начала проекта? Или последние удаление компонентов восстановления пароля и ещё тикет чтобы их вернуть к месту?

2024-02-06 16:22 UTC, RomanAnurov commented on src/components/Popups/InfoPopup/InfoPopup.tsx
> +    }, [navigate]);
вчера я пофиксил и не было конфликтов. А теперь появился

2024-02-06 16:35 UTC, RomanAnurov commented on src/pages/NewPassword/NewPassword.tsx
> +        setIsLoading(false);
Если про удаление вышеуказанных компонентов то вот они https://github.com/orgs/bronfood-com/projects/1/views/1?pane=issue&itemId=52297719
https://github.com/orgs/bronfood-com/projects/1/views/1?pane=issue&itemId=52298663

2024-02-06 16:35 UTC, merged