console allowed in development
bronfood-com/front pull request #49
Opened 2024-02-03 12:46 UTC by SergeyGetmanskiy

1. В файле .env надо прописать NODE_ENV=development
2. Установить npm install dotenv --save
И тогда если NODE_ENV = development, то eslint выдает варнинги, а если NODE_ENV = production, то выдает error

2024-02-05 10:16 UTC, cronon requested changes

2024-02-05 10:16 UTC, cronon commented on .eslintrc.cjs
> +require('dotenv').config();
а как будет работать без dotenv? 
По идее, локально process.env.NODE_ENV будет undefined, а на сиае будет production, то есть можно обойтись без него

2024-02-05 13:17 UTC, SergeyGetmanskiy commented on .eslintrc.cjs
> +require('dotenv').config();
без dotenv нет доступа к переменным из .env файла.
Вот здесь написано, что по умолчанию process.env.NODE_ENV будет скорее development, чем undefined. https://nodejs.org/en/learn/getting-started/nodejs-the-difference-between-development-and-production
У меня локально по умолчанию NODE_ENV=development. Поэтому да, согласен, что нет смысла в дев-режиме устанавливать значение NODE_ENV . Вообщем файл .env удалил, из package.json убрал dotenv

2024-02-05 14:07 UTC, cronon commented on package-lock.json
если список зависимостей не менялся в package.json, то и этот файл надо чтобы не менялся

2024-02-05 14:07 UTC, cronon commented on .eslintrc.cjs
> +require('dotenv').config();
попробуй плз закоммитить теперь console.log и посмотреть, что сиай на это скажет

2024-02-05 14:08 UTC, cronon commented on .eslintrc.cjs
> +require('dotenv').config();
попробуй плз закоммитить теперь console.log и посмотреть, что сиай на это скажет

2024-02-05 15:35 UTC, SergeyGetmanskiy commented on .eslintrc.cjs
> +require('dotenv').config();
закоммитил. Сиай выдал варнинг. 
![image](https://github.com/bronfood-com/front/assets/122983365/de7734b0-8023-4357-ac2c-f5e3c1b20851)

2024-02-05 15:36 UTC, SergeyGetmanskiy commented on package-lock.json
откатил изменения здесь

2024-02-05 15:44 UTC, cronon commented on .eslintrc.cjs
> +require('dotenv').config();
Это тебе пре-коммит хук не дал коммит сделать. 
сиай - это CI - continuous integration - это сервер, который запускает билд для каждого коммита в пул-реквестах и не дает мержить ПРы, если билд не проходит
![image](https://github.com/bronfood-com/front/assets/4602009/96e715c7-0715-4e12-923a-3796e4e4d075)

Сделай коммит в обход пре-коммит хука, и запушь код. Надо сделать так, чтобы когда был console.log, то эта штука была бы красная и не давала бы смержить твой ПР

2024-02-05 16:08 UTC, SergeyGetmanskiy commented on .eslintrc.cjs
> +require('dotenv').config();
Ci ожидаемо выдал ошибку с console.log
![image](https://github.com/bronfood-com/front/assets/122983365/2f99ea2d-05f2-4e63-9d46-77f135fec735)

2024-02-06 12:41 UTC, cronon approved these changes

2024-02-06 12:47 UTC, SergeyGetmanskiy commented on package.json
> +    "lint:prod": "NODE_ENV=production eslint",
убрал

2024-02-06 12:55 UTC, merged