Bugfix/clear errormessage
bronfood-com/front pull request #51
Opened 2024-02-08 07:54 UTC by SergeyGetmanskiy

2024-02-08 14:37 UTC, cronon requested changes

2024-02-08 14:37 UTC, cronon commented on src/components/Popups/Popup/Popup.tsx
> +    const { setErrorMessage } = useCurrentUser();
общий юай компонент не должен ничего знать лишнего о юзере и моделе. Тогда мы сможем его легко юзать во всех местах и не задумываться о CurrentUser.

А вот конкретные компоненты SignIn и SignUp вполне могут знать все конкретные детали

2024-02-08 14:37 UTC, cronon commented on src/contexts/CurrentUserContext.tsx
>      errorMessage: string | null;
я теперь думаю, что лучше всего будет, чтобы были отдельные поля с ошибками для singIn, signUp и logout. Это разные вызовы, и как ни крути у них будут разные ответы. И это будет просачиваться в места, которые используют UserContext
Можно сделать по такой схеме
```
signIn: {
  mutaiton: (data: FieldValues) => Promise<void> // мутация, то есть она что-то изменяет на сервере
  isLoading; boolean;
  errorMessage: string | null
 }
 и остальные методы так же
 ```

Остается открытым вопрос, что делать если я зафейлил логин, потом нажал на крестик, а потом опять открыл страницу входа.
Я думаю так: если набранный телефон и пароль остается, то пусть и сообщение об ошибке остается. Если пропадают, то и сообщение об ошибке должно пропадать. Этот момент тогда должен хэндлится в юае, а не в модели. То есть придется завести стейт errorVisible и делать его true когда нажимаешь на Войти и false когда нажимаешь на крестик

2024-02-09 10:11 UTC, SergeyGetmanskiy commented on src/contexts/CurrentUserContext.tsx
>      errorMessage: string | null;
Вот это я реализовал: 
![image](https://github.com/bronfood-com/front/assets/122983365/c2480245-14a4-45eb-9a60-cb5c3c43a627)

А с остальным проблема.
Не пойму, как компоненты SignIn и Signup при их открытии знают, что "_набранный телефон и пароль остается_". Поэтому не понимаю как и в каком компоненте мне реализвать стейт errorVisible ?

2024-02-09 10:12 UTC, SergeyGetmanskiy commented on src/components/Popups/Popup/Popup.tsx
> +    const { setErrorMessage } = useCurrentUser();
починил

2024-02-09 10:54 UTC, cronon commented on src/contexts/CurrentUserContext.tsx
> +    const [isLoading, setIsLoading] = useState<boolean>(false);
Loading тоже нужен разный на всех с той точки зрения, что физически какбы можно все эти запросы одновременно запустить и они разрешаться какждый в свое время.
Но логически это неправильно. Допустим я в рядок написал signIn.mutation() signUp.mutation(), logout.mutation() но ответ для логаута загрузился самый первый, а для входа - последний. В каком состоянии теперь должен быть currentUser и isLogin? Сам я не знаю. Пускай эта задача остается у тебя в голове и решается на фоне) 
Сделай пожалуйста тикет для нее и положи в бэклог. Сейчас она не особо критична, все-таки с юая нельза одновременно нажать на логин и логаут

А вообще ситуации такого плана называются race conditions и скоро мы с ней опять столкнемся когда у нас будет больше запросов на рестораны, добавление в корзину и т.п.

2024-02-09 10:58 UTC, cronon commented on src/contexts/CurrentUserContext.tsx
>      errorMessage: string | null;
если не остается набранный телефон и пароль, то не нужен errorVisible

2024-02-09 14:45 UTC, SergeyGetmanskiy commented on src/contexts/CurrentUserContext.tsx
>      errorMessage: string | null;
Добавил в модель метод очистки сообщения об ошибке (clearErrorMessage). Он вызывается только в компоненте Popup при нажатии на крестик

2024-02-09 14:51 UTC, SergeyGetmanskiy commented on src/contexts/CurrentUserContext.tsx
> +    const [isLoading, setIsLoading] = useState<boolean>(false);
В бэклог добавил!

2024-02-11 10:36 UTC, cronon commented on src/contexts/CurrentUserContext.tsx
> +    const [isLoading, setIsLoading] = useState<boolean>(false);
добавь плз ссылку сюда на тикет

2024-02-11 10:41 UTC, cronon commented on src/contexts/CurrentUserContext.tsx
>      errorMessage: string | null;
А в мастере набранный телефон и пароль остается если закрыть попап и опять его открыть?

2024-02-11 10:46 UTC, cronon commented on src/contexts/CurrentUserContext.tsx
>      errorMessage: string | null;
В модели не должно быть такого метода. Ошибка там произошла и с этим ничего не поделаешь. Однако конкретные юайные компоненты могут решить показывать ее или нет. Соответственно и стейт "показывать ошибку или нет" должен принадлежать конкретным компонентам.

В модели лежит как бы чистая дистилированная информация о бизнес-сущности, а в компонентах лежат стейты о том, как эту информацию представлять.

2024-02-11 10:55 UTC, cronon requested changes

2024-02-11 10:55 UTC, cronon commented on src/components/Popups/Popup/Popup.tsx
> +    clearErrorMessage?: () => void;
Интерфейсы компонентов должны касаться только их самих, так проще. Компонент Popup ничего не знает про еррормессаджи. Он только знает что у него есть кнопка закрытия. Так и пишем `onClose: () => void`. А пользователи компонента Popup будут сами решать что делать по onClose.

Если оставить clearErrorMessage, то чтобы использовать Popup для какой-нибудь другой страницы и делать там действие по закрытию попапа, мне придется запомнить "Есть Popup, и когда он закрывается он делает clearErrorMessage потому что так сделано на SignIn и SignUp страницах."

Если сделать onClose, то чтобы делать действие во время закрытия попапа мне надо знать "Есть попап и когда он закрывается он делает onClose"

2024-02-11 10:56 UTC, cronon commented on src/contexts/CurrentUserContext.tsx
> +            setLogoutErrorMessage('logout error');
добавь плз сюда ссылку на контракт, если они не апрувнули, то заведи еще пожалуйста тикет на это, чтобы нам не потерять этот момент

2024-02-11 12:34 UTC, SergeyGetmanskiy commented on src/contexts/CurrentUserContext.tsx
> +            setLogoutErrorMessage('logout error');
Бэки пока молчат, поэтому добавил тикет в бэклог
https://github.com/orgs/bronfood-com/projects/1/views/1?pane=issue&itemId=52896394

2024-02-11 12:36 UTC, SergeyGetmanskiy commented on src/contexts/CurrentUserContext.tsx
> +    const [isLoading, setIsLoading] = useState<boolean>(false);
https://github.com/orgs/bronfood-com/projects/1/views/1?pane=issue&itemId=52796903

2024-02-11 13:28 UTC, SergeyGetmanskiy commented on src/components/Popups/Popup/Popup.tsx
> +    clearErrorMessage?: () => void;
Спасибо за коммент! Исправил. В Popup теперь только метод onclose()

2024-02-11 15:40 UTC, SergeyGetmanskiy commented on src/contexts/CurrentUserContext.tsx
>      errorMessage: string | null;
Кажется получилось сделать, чтобы когда открыл попап -> фейл -> -> появилось сообщение об ошибке -> закрыл попап -> открыл попап -> сообщение об ошибке не показывается. Даже если сообщение об ошибке осталось в модели. Сдеал это для SignIn и SignUp

2024-02-12 16:23 UTC, cronon commented on src/contexts/CurrentUserContext.tsx
> +    const [isLoading, setIsLoading] = useState<boolean>(false);
А в тикете - добавь пожалуйста ссылку на коммент, который ты заскринил, чтобы потом человек мог открыть ПР и выяснить весь контекст

2024-02-12 16:25 UTC, cronon commented on src/contexts/CurrentUserContext.tsx
>      errorMessage: string | null;
Мастер - master бранч. По дефолту в гите так называется самый главный бранч. В гитхабе несколько лет назад сделали, чтобы он назывался main, теперь мастер и мэин обозначают одно и тоже - main бранч

2024-02-12 16:31 UTC, cronon approved these changes

2024-02-12 16:58 UTC, SergeyGetmanskiy commented on src/contexts/CurrentUserContext.tsx
> +    const [isLoading, setIsLoading] = useState<boolean>(false);
Добавил

2024-02-12 16:59 UTC, merged