Feature/client api
bronfood-com/front pull request #55
Opened 2024-02-18 11:19 UTC by vitland

Добавил реальный апи. 
В ПР используется моковый, который отдает идентичные данные реальному.

2024-02-19 13:54 UTC, cronon requested changes

2024-02-19 13:54 UTC, cronon commented on src/utils/api/auth.ts
> +    confirmation_code: string;
в чем разница между temp_data_code и confirmation_code? Сделай пожалуйста jsdoc для интерфейсов

2024-02-19 13:54 UTC, cronon commented on src/utils/api/auth.ts
> +class AuthApi {
прикрепи сюда плз в коммент ссылку на контракт в ноушене

2024-02-19 13:54 UTC, cronon commented on src/utils/api/auth.ts
> +    async loguOut(token: string): Promise<{ status: string }> {
```suggestion
    async logOut(token: string): Promise<{ status: string }> {
```

2024-02-19 13:54 UTC, cronon commented on src/utils/api/auth.ts
> +    auth_token: string;
пускай токен не вылезает за пределы сервиса (то есть класса AuthApi), и пусть сервис сам его хранит или достает и сохраняет.
Мы можем спрятать токен внутри сервиса и не нагружать этой информацией тех, кто будет в других местах пользоваться интерфейсом User. Интерфейс станет проще и цена за это небольшая

2024-02-19 13:54 UTC, cronon commented on src/utils/api/mockAuth.ts
> +
настоящий и моковый сервис должен использовать те же самые интерфейсы и типы. Не просто которые выглядят одинаково, а чтобы это были одни и теже сущности
Тогда мы сможем легко переключаться между моковым и настоящим сервисом и все будет работать - у нас будет гарантия на уровне типов, что оба сервиса выдают объекты одинаковой формы

Для верности, стоит добавить интерфейс в котором будут описаны методы login/register/logout - все, что нужно юайной части от интерфейса. Моковый и настоящий сервис будут его имплементировать.
```
interface AuthService { login().... }
class AuthServiceReal implements AuthService  { login(){ return fetch(....) ... }
class AuthServiceMock implements AuthService { login() {return {fullname: 'user' ... } }
```
и теперь из папки с сервисами экспортируется только какая-то вещь типа AuthService, и остальные места приложения никогда не должны знать какая именно
```
// utils/api/auth.ts
export const authService: AuthService = new AuthServiceReal() // new AuthServiceMock() 

// contexts/CurrentUserContext.tsx
import {authService} from ' .... auth'
и здесь юзается исключительно то, что написано в интерфейсе AuthService  и больше ничего
```
таким образом, всем юайным местам не надо будет знать ни о каких особенностях через докер ли запросы делаются или это моки. И переключение будет сделано только в одном месте

2024-02-19 13:54 UTC, cronon commented on src/utils/consts.tsx
> +export const API_URL = 'http://127.0.0.1:8000';
Добавь пожалуйста в ридми инструкцию как ты запускаешь докер

2024-02-19 13:54 UTC, cronon commented on src/utils/api/mockAuth.ts
> +    async loguOut(token: string): Promise<{ status: 'success' } | { status: 'error'; error_message: string }> {
```suggestion
    async logOut(token: string): Promise<{ status: 'success' } | { status: 'error'; error_message: string }> {
```

2024-02-23 08:32 UTC, vitland commented on src/utils/api/auth.ts
> +interface confirmRegisterPhoneData {
Добавил

2024-02-23 08:35 UTC, vitland commented on src/utils/api/auth.ts
> +    confirmation_code: string;
Добавил

2024-02-23 08:36 UTC, vitland commented on src/utils/api/auth.ts
> +interface confirmRegisterPhoneData {
Исправил

2024-02-23 19:49 UTC, vitland commented on src/utils/api/auth.ts
> +    auth_token: string;
Поменял

2024-02-23 19:49 UTC, vitland commented on src/utils/api/mockAuth.ts
> +
Сделал

2024-02-23 19:56 UTC, vitland commented on src/utils/consts.tsx
> +export const API_URL = 'http://127.0.0.1:8000';
добавил

2024-02-23 19:56 UTC, vitland commented on src/utils/api/mockAuth.ts
> +    async loguOut(token: string): Promise<{ status: 'success' } | { status: 'error'; error_message: string }> {
исправил

2024-02-23 19:57 UTC, vitland commented on src/utils/api/auth.ts
> +    async loguOut(token: string): Promise<{ status: string }> {
исправил

2024-02-25 10:23 UTC, cronon commented on src/utils/api/authService.ts
> +    logOut: () => void;
```suggestion
    logOut: () => Promise<void>;
```

2024-02-25 10:23 UTC, cronon commented on src/utils/api/authService.ts
> +    getToken: () => string | null;
в юае у нас этим методом никто не пользуется, поэтому можно его убрать

2024-02-26 18:49 UTC, vitland commented on src/utils/api/authService.ts
> +    logOut: () => void;
Поменял

2024-02-26 18:49 UTC, vitland commented on src/utils/api/authService.ts
> +    getToken: () => string | null;
Убрал

2024-02-27 10:50 UTC, cronon approved these changes

2024-02-27 10:55 UTC, merged