Страница Profile( не доделана нужна помощь)
bronfood-com/front pull request #56
Opened 2024-02-18 20:54 UTC by RomanAnurov

Я запутался. По аналогии с ранее сделанным сделал. В АПИ. Вм контексте и в самом компоненте. Что-то после редактирования новый Юзер в локал сторадж не перезаписывается.

И ещё вопрос при редактировании например только имени или телефона .В этом компоненте и пароль нужно вводить и подтверждать?  Но у нас же есть другой компонент для смены пароля. Что-то я запутался

2024-02-19 14:00 UTC, cronon requested changes

2024-02-19 14:00 UTC, cronon commented on src/contexts/CurrentUserContext.tsx
> Что-то после редактирования новый Юзер в локал сторадж не перезаписывается.

Надо дебажить. Поставь console.log в разных местах по дороге от нажатия на кнопку до localStore.setItem и будет видно в каком месте перестает работать

> И ещё вопрос при редактировании например только имени или телефона .В этом компоненте и пароль нужно вводить и подтверждать? Но у нас же есть другой компонент для смены пароля. Что-то я запутался

Этот вопрос надо адресовать заказчику

2024-02-22 19:55 UTC, RomanAnurov commented on src/contexts/CurrentUserContext.tsx
Сделал ещё два дня назад чтобы пользователь перезаписывался в local storage. Но вот правильно ли это работает? Почему при регистрации одни ключи, а при редактировании по другому и пароли заносятся в хранилище?
![001](https://github.com/bronfood-com/front/assets/99470278/abb411cd-201c-4fad-9a4b-d6eff92cd265)
![002](https://github.com/bronfood-com/front/assets/99470278/ade3ac31-12e2-42fe-8bd0-6e136775ab25)

2024-02-28 18:02 UTC, RomanAnurov commented on src/contexts/CurrentUserContext.tsx
@cronon Сделал вначале по аналогии с регистрацией, сохранялось в компоненте контекста эзера CurrentUserContext. 
![ggg01](https://github.com/bronfood-com/front/assets/99470278/c7cd15e7-0492-479a-9a1a-7e2cd6a4ea79)
При регистрации получалось в хранилище "name":"User". Но при обновлении данных юзера по моему коду в localStorage ничего не менялось. Я тогда написал сохранение в самом компоненте Profile и юзер обновлялся 'username': "Серёга"
![ggg02](https://github.com/bronfood-com/front/assets/99470278/91987b49-0112-45fc-9cd1-1802e9d07dbc)

2024-02-29 16:42 UTC, cronon commented on src/contexts/CurrentUserContext.tsx
нужно дебажит, поставь везде console.log по дороге от клика к localsStorage.setItem и проследи где console.log пишет не ту инфу, которую ты ожидаешь

2024-02-29 16:43 UTC, RomanAnurov commented on src/contexts/CurrentUserContext.tsx
Хорошо понял продебажу

2024-02-29 17:07 UTC, cronon commented on src/utils/api/auth.ts
> +
прочекай плз с контрактом в ноушене, чтобы у тебя совпадали названия полей

2024-02-29 17:43 UTC, cronon commented
1. Спросить у кастомера как должно работать, нужно ли обязательно писать новый пароль каждый раз
2. Показывать текущий телефон и емейл в инпутах
3. Моковый апи как в контракте
4. Запустить докер
5. Настоящий апи как в контракте

2024-03-01 16:31 UTC, RomanAnurov commented on src/utils/api/auth.ts
> +
Прочекал подкорректирую

2024-03-05 12:27 UTC, cronon commented
Роман ушел, отклоняем ПР до лучших времен

2024-03-05 12:27 UTC, closed without merging