Feature/drawer layout
bronfood-com/front pull request #57
Opened 2024-02-25 07:37 UTC by SergeyGetmanskiy

2024-02-25 11:07 UTC, cronon requested changes

2024-02-25 11:07 UTC, cronon commented on src/App.tsx
Сделай пожалуйста из мастера ветку feature/restaurants - это будет фича-бранчем для всех экранов из твоего тикета Нацель туда этот ПР и остальные все (наверное) ПРы тоже туда пойдут. А потом смержим  feature/restaurants в мастер

А в описании к этому ПРу напиши список какие ПРы ты планируешь делать дальше

2024-02-25 17:26 UTC, SergeyGetmanskiy commented on src/components/Drawer/Drawer.tsx
> +type Props = {
починил

2024-02-25 17:45 UTC, SergeyGetmanskiy commented on src/pages/Restaurants/Restaurants.tsx
> +    const [isDrawerOpen, setIsDrawerOpen] = useState(false);
починил

2024-02-25 18:01 UTC, SergeyGetmanskiy commented on src/components/Drawer/Drawer.tsx
> +                <button onClick={toggleDrawer} type="button" className={styles.drawer__line_container}>
написал заказчику в ноушене

2024-02-25 18:02 UTC, SergeyGetmanskiy commented on src/App.tsx
> +                <Route path="/restaurants" element={<ProtectedRoute component={<Restaurants />} />} />
должно сюда перебрасывать если установлен currentUser

2024-02-27 10:59 UTC, SergeyGetmanskiy commented on src/components/Drawer/Drawer.tsx
> +                <ul className={styles.drawer__list}>
Как ни старался, так и не увидел горизонтального скрола у себя). 
Ресторан по центру выделяется оранжевой рамкой. Для этого использовал хук useInView библиотеки [framer-motion](https://www.framer.com/motion/use-in-view/). Этот хук следит за положением элемента при скролле и если элемент приблизительно по центру, то хук возвращает true. Хук положил в ReastaurantCard. Центровку положения карточки ресторана можно регулировать с помощью опции margin хука.

2024-02-27 10:59 UTC, SergeyGetmanskiy commented on src/components/Drawer/Drawer.tsx
> +                <ul className={styles.drawer__list}>
В css теперь есть свойство, которое не дает скроллить как хочешь, а скролит прицельно по одному блоку

А что за свойство?

2024-02-27 11:37 UTC, SergeyGetmanskiy commented on src/components/Drawer/Drawer.tsx
> +    direction?: DrawerDirection;
1. direction.down убрал.
2. Drawer положил в Restaurants.

2024-02-27 11:48 UTC, SergeyGetmanskiy commented on src/App.tsx
Сделал

2024-02-27 12:06 UTC, SergeyGetmanskiy commented on src/pages/Main/Main.tsx
> +    }, [navigate]);
у меня тоже на превью пулл реквестов не перенаправляет сразу на рестораны. Перенаправляет только, когда в коде сработает первый useNavigate. Например сюда ('/') или сюда ('/restaurants'). Вообще странно как то работает роуинг на превью в gh-pages. Я ещё с экраном 404 намучился)). Может нам перейти на превью в Vercel ?

2024-02-28 14:30 UTC, cronon commented on src/components/Drawer/Drawer.tsx
> +                <ul className={styles.drawer__list}>
https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_scroll_snap
кстати только недавно в Мастерской от студентов про него узнал)

2024-02-28 14:35 UTC, cronon commented on src/components/Drawer/Drawer.tsx
> +                <ul ref={container} className={styles.drawer__list}>
![image](https://github.com/bronfood-com/front/assets/4602009/d2e15fdf-bcb3-43c3-b7e7-fb0cb7c48b5c)
Горизонтальный скролл у меня остается на любом разрешении, 1920 или меньше
Опера и Хром, Windows 11

2024-02-28 14:35 UTC, cronon commented on src/pages/Main/Main.tsx
> +    }, [navigate]);
Надо разбираться

а чем лучше будет Vercel?

2024-02-28 14:37 UTC, cronon commented on src/App.tsx
Подожди, кроме верстки в рамках этого тикета еще нужна и логика, и вызовы апи, и чтобы в списке показывались рестораны которые на карте показаны и вообще все

2024-02-29 11:50 UTC, SergeyGetmanskiy commented on src/App.tsx
добавил соответствующие пункты в описание к этому ПР

2024-02-29 16:39 UTC, cronon commented on src/App.tsx
А что входит в логику? Лучше раздели ее на части, и я думаю, что таски с логикой будут перекрываться с версткой, и будет проще их вместе делать. Разве что какую-то особо сложную верстку или логику можно вынести.

Напиши так, чтобы можно было посмотреть на эти пункты и легко понять, готовы они или нет

2024-02-29 19:45 UTC, SergeyGetmanskiy commented on src/pages/Main/Main.tsx
> +    }, [navigate]);
> Надо разбираться
> 
> а чем лучше будет Vercel?

В одном своем пет-проекте я задеплоил на Vercel и проблема с роутингом решилась одной строчкой в конфиге versel.json: 
{
  "rewrites": [{ "source": "/(.*)", "destination": "/" }]
}

2024-02-29 19:53 UTC, SergeyGetmanskiy commented on src/components/Drawer/Drawer.tsx
> +                <ul className={styles.drawer__list}>
Спасибо за ссылку. Заюзал scroll-snap-type у контейнера и scroll-snap-align: start у элемента списка. И теперь скролл работает предсказуемо (верхняя карточка верхним краем автоматически выравнивается по верхнему краю вьюпорта.
Что касается оранжевой рамки вокруг центральной карточки, то решил всё таки оставить библиотеку. Так как она со своей работой справляется. Кроме того, в ней задействован ref карточки ресторана, который потом пригодится для синхронизации с маркером данного ресторана на карте (о чем говорил заказчик).

2024-02-29 20:06 UTC, SergeyGetmanskiy commented on src/App.tsx
отредактировал пункты. продублировал их в тикет [Ресторан ](https://github.com/orgs/bronfood-com/projects/1/views/1?pane=issue&itemId=52648495)

2024-03-01 12:58 UTC, cronon commented on src/pages/Main/Main.tsx
> +    }, [navigate]);
а какая была проблема с роутингом?

2024-03-01 13:05 UTC, cronon commented on src/pages/Restaurants/Drawer/Drawer.tsx
> +const Drawer = ({ isOpen, title, list, toggleDrawer, openFilter, openListItem }: DrawerProps) => {
![image](https://github.com/bronfood-com/front/assets/4602009/56407e75-c0af-484e-9e22-980cf8770004)
В фигме список ресторанов обрезается нижней границей экрана, а у нас еще много места есть.

Кстати, спроси заодно пожалуйста у дизайнера может ли оранжевая рамка показываться на самом последнем элементе в списке.

2024-03-02 09:07 UTC, SergeyGetmanskiy commented on src/pages/Restaurants/Drawer/Drawer.tsx
> +const Drawer = ({ isOpen, title, list, toggleDrawer, openFilter, openListItem }: DrawerProps) => {
> В фигме список ресторанов обрезается нижней границей экрана, а у нас еще много места есть.

Не понял ,что ты имеешь ввиду. Можно ли показывать не 2,5 карточки, а 3 целых карточки? Но тогда надо увеличить высоту дравера.

2024-03-02 09:10 UTC, SergeyGetmanskiy commented on src/pages/Restaurants/Drawer/Drawer.tsx
> +const Drawer = ({ isOpen, title, list, toggleDrawer, openFilter, openListItem }: DrawerProps) => {
> > В фигме список ресторанов обрезается нижней границей экрана, а у нас еще много места есть.
> 
> Не понял ,что ты имеешь ввиду. Разве место, которое ты обозначил, мы можем как-то использовать ?

2024-03-02 09:23 UTC, SergeyGetmanskiy commented on src/pages/Main/Main.tsx
> +    }, [navigate]);
Например,  к урлу превью ПР https://bronfood-com.github.io/front/pr-preview/pr-57/ или превью мастера https://bronfood-com.github.io/front/ нельзя добавить вручную ни одного нашего роута, гитхаб выкидывает 404 страницу.
Если перешел на роут кликом ,то после перезагрузки страницы , опять выкидывает 404.
Всё это не дает, например, увидеть нашу собственную страницу 404 в продакшене.

2024-03-04 15:50 UTC, cronon commented on src/pages/Main/Main.tsx
> +    }, [navigate]);
понял
пока что я настроен терпеть гитхаб, чем переходить на vercel, много надо сиай менять и у кастомера разрешение просить. Но ты создай пожалуйста таску в бэклоге и опиши там проблему с гитхабом и как версел ее решает. И будем в этом тикете трекать дальнейшие проблемы с гитхабом. Если они и дальше будут часто происходить, то перейдем.

2024-03-04 15:57 UTC, cronon commented on src/pages/Restaurants/Drawer/Drawer.tsx
> +const Drawer = ({ isOpen, title, list, toggleDrawer, openFilter, openListItem }: DrawerProps) => {
>Не понял ,что ты имеешь ввиду. Разве место, которое ты обозначил, мы можем как-то использовать ?

Можем, а что тебя смущает? Пусть скролбар доходит до самого низа

>Можно ли показывать не 2,5 карточки, а 3 целых карточки? Но тогда надо увеличить высоту дравера.

Ага, это надо у кастомера уточнять. Можно драверу сделать высоту фиксированной, тогда будет 2.5 карточки и скролбар до низу.
* Можно сделать высоту в процентах, тогда надо будет показывать больше карточек, и скролбар до низу.
* Можно выбрать вариант который тебе легче имплементировать, и заказчика уведомить об этом, и заодно в фигме написать, чтобы не потерялось.

>Кстати, спроси заодно пожалуйста у дизайнера может ли оранжевая рамка показываться на самом последнем элементе в списке.

2024-03-04 17:13 UTC, SergeyGetmanskiy commented on src/pages/Restaurants/Drawer/Drawer.tsx
> +const Drawer = ({ isOpen, title, list, toggleDrawer, openFilter, openListItem }: DrawerProps) => {
В Фигме оставил [вопрос про 2,5 карточки.](https://www.figma.com/file/9H7H1cGkW9CYB7iFRpm7x3?node-id=647:6522&mode=design#722895615).
Текущую реализацию пока оставляем без изменений?

2024-03-04 17:24 UTC, SergeyGetmanskiy commented on src/pages/Main/Main.tsx
> +    }, [navigate]);
Создал [тикет.](https://github.com/orgs/bronfood-com/projects/1/views/1?pane=issue&itemId=55296872)

2024-03-04 18:53 UTC, SergeyGetmanskiy commented on src/pages/Restaurants/Drawer/Drawer.tsx
> +const Drawer = ({ isOpen, title, list, toggleDrawer, openFilter, openListItem }: DrawerProps) => {
пришел [ответ про 2,5 карточки](https://www.figma.com/file/9H7H1cGkW9CYB7iFRpm7x3?node-id=647:6522&mode=design#722895615)

2024-03-04 18:56 UTC, SergeyGetmanskiy commented on src/pages/Restaurants/Drawer/Drawer.tsx
> +const Drawer = ({ isOpen, title, list, toggleDrawer, openFilter, openListItem }: DrawerProps) => {
пришел [ответ про оранжевую рамку](https://www.figma.com/file/9H7H1cGkW9CYB7iFRpm7x3?node-id=647:6522&mode=design#722901079)

2024-03-05 08:10 UTC, SergeyGetmanskiy commented on src/pages/Restaurants/Drawer/Drawer.tsx
> +const Drawer = ({ isOpen, title, list, toggleDrawer, openFilter, openListItem }: DrawerProps) => {
дизайнер исправила [фигму](https://www.figma.com/file/9H7H1cGkW9CYB7iFRpm7x3?node-id=647:6522&mode=design#722895615), теперь там 3 целых карточки

2024-03-05 12:25 UTC, cronon commented on src/pages/Restaurants/Drawer/Drawer.tsx
> +const Drawer = ({ isOpen, title, list, toggleDrawer, openFilter, openListItem }: DrawerProps) => {
1 В фигме высота кнопки 30, а здесь в превью - 36
2 Расстояние между скролбаром и нижней границей экрана в фигме 0, в превью - очень много

![image](https://github.com/bronfood-com/front/assets/4602009/eb9330bd-5744-4ffa-9e8c-528cac1357e3)

2024-03-05 16:25 UTC, SergeyGetmanskiy commented on src/pages/Restaurants/Drawer/Drawer.tsx
> +const Drawer = ({ isOpen, title, list, toggleDrawer, openFilter, openListItem }: DrawerProps) => {
1. Высоту исправил на 30.
2. Лишнее расстояние убрал.

2024-03-05 16:27 UTC, cronon approved these changes

2024-03-05 16:28 UTC, merged