Feature/restaurant context and filter
bronfood-com/front pull request #58
Opened 2024-03-05 19:43 UTC by SergeyGetmanskiy

2024-03-06 15:03 UTC, cronon requested changes

2024-03-06 15:03 UTC, cronon commented on src/pages/Restaurants/Filter/OptionElement/OptionElement.tsx
> +            <p className={styles.option__text}>{props.text}</p>
p - это параграф - это такой текст, который надо читать потому, что тебе интересно узнать информацию, которая там написана. В общем, этот элемент нагружен смыслом. А еще его не везде можно вставлять. Например, если сделать параграф внутри параграфа, то браузер отрендерит их один за одним, а не один внутри другого.
Внутри контролов лучше использовать спан или див - не ошибешься

2024-03-07 08:00 UTC, SergeyGetmanskiy commented on src/contexts/RestaurantsContext.tsx
> +    };
стейты компонентов переместил из контекста обратно в компоненты.

2024-03-07 09:25 UTC, SergeyGetmanskiy commented on src/contexts/RestaurantsContext.tsx
> +    const [restaurantsOnMap, setRestaurantsOnMap] = useState<Restaurant[]>([]);
починил

2024-03-07 09:28 UTC, SergeyGetmanskiy commented on src/contexts/RestaurantsContext.tsx
> +            await restaurant.meals.forEach((meal) => {
async/await убрал. планировал это убрать, но забыл перед ПР)

2024-03-07 12:38 UTC, SergeyGetmanskiy commented on src/contexts/RestaurantsContext.tsx
> +    const options = useMemo(() => {
сделал

2024-03-07 12:39 UTC, SergeyGetmanskiy commented on src/contexts/RestaurantsContext.tsx
> +    }, [restaurantsOnMap]);
> здесь и в types: restaurantsOnMap у нас не меняются, поэтому пусть options и types генерируются тоже за пределами хука. Например в файле мока рядом с mockRestaurants

сделал

2024-03-07 12:48 UTC, SergeyGetmanskiy commented on src/contexts/RestaurantsContext.tsx
> +    }, [restaurantsOnMap]);
> Кстати, я об этом особо не думал, подозреваю, что доступные фильтры тоже надо с бэка получать. Например у нас на карте показано только одно "кафе", надо ли будет показывать юзерам что у нас еще другие категории есть, не только "кафе"?

Подобный [вопрос](https://www.figma.com/file/9H7H1cGkW9CYB7iFRpm7x3?node-id=647:6536&mode=design#723950881) я задал заказчику, но ответа пока нет

2024-03-07 12:53 UTC, SergeyGetmanskiy commented on src/contexts/RestaurantsContext.tsx
> +    const types = useMemo(() => {
useMemo убрал

2024-03-07 15:09 UTC, SergeyGetmanskiy commented on src/contexts/RestaurantsContext.tsx
> +            const filtered = restaurantsOnMap.filter((restaurant) => {
сделал.

2024-03-07 15:27 UTC, SergeyGetmanskiy commented on src/contexts/RestaurantsContext.tsx
> +    const [venueTypes, setVenueTypes] = useState<VenueType[]>([]);
потому что я задумывал options и selectedOptions как два независящих друг от друга списка. 
options.all используется только в автокомплите(это фактически чистый список всех возможных опций(название заведения, продукт, блюдо) , который не мутируется ,сейчас он лежит в файле вместе с моковыми ресторанами) , а selectedOptions - это стейт, который легко изменяется. 
Можно было бы options и selectedOptions как то объединить, на подобие venueTypes, но решил этого не делать.
Может, оставим как есть?))

2024-03-07 18:14 UTC, SergeyGetmanskiy commented on src/pages/Restaurants/Filter/Filter.tsx
> +            const linked = options.all.filter((opt) => opt.name.toLowerCase().indexOf(userInput.toLowerCase()) > -1);
починил

2024-03-07 18:47 UTC, SergeyGetmanskiy commented on src/pages/Restaurants/Filter/ButtonElement/ButtonElement.tsx
> +        </button>
починил

2024-03-07 18:50 UTC, SergeyGetmanskiy commented on src/pages/Restaurants/Filter/ButtonElement/ButtonElement.tsx
> +const ButtonElement = (props: ButtonElementProps) => {
починил

2024-03-07 19:01 UTC, SergeyGetmanskiy commented on src/pages/Restaurants/Filter/ButtonElement/ButtonElement.tsx
> +    action: () => void;
починил. В OptionElement тоже исправил

2024-03-07 19:03 UTC, SergeyGetmanskiy commented on src/pages/Restaurants/Filter/OptionElement/OptionElement.tsx
> +            <p className={styles.option__text}>{props.text}</p>
починил

2024-03-08 13:01 UTC, cronon commented on src/pages/Restaurants/MockRestaurantsList.ts
> +    .filter((type, i, ar) => ar.indexOf(type) === i)
а, ну можем и установить lodash, там есть функция unique, делает именно это. Или потом установим, когда в следующий раз что-нибудь оттуда понадобится

2024-03-08 13:03 UTC, cronon commented on src/contexts/RestaurantsContext.tsx
> +    const [venueTypes, setVenueTypes] = useState<VenueType[]>([]);
а как насчет сделать список venueTypes.all и selectedVenueTypes?

2024-03-08 15:54 UTC, SergeyGetmanskiy commented on src/contexts/RestaurantsContext.tsx
> +type RestaurantsContext = {
сделал

2024-03-08 16:11 UTC, SergeyGetmanskiy commented on src/contexts/RestaurantsContext.tsx
> +        setRestaurantsOnMap(mockRestaurants);
useEffect убрал

2024-03-08 17:02 UTC, SergeyGetmanskiy commented on src/pages/Restaurants/MockRestaurantsList.ts
> +                { id: id++, name: meal.name },
написал фукцию increment

2024-03-08 17:04 UTC, SergeyGetmanskiy commented on src/pages/Restaurants/MockRestaurantsList.ts
> +    .filter((type, i, ar) => ar.indexOf(type) === i)
я изначально думал установить lodash, но потом посчитал, что из-за 2-3 функций не стоит

2024-03-08 17:05 UTC, SergeyGetmanskiy commented on README.md
добавил

2024-03-09 08:27 UTC, SergeyGetmanskiy commented on src/contexts/RestaurantsContext.tsx
> +    const [venueTypes, setVenueTypes] = useState<VenueType[]>([]);
сделал venueTypes по аналогии с options

2024-03-09 09:18 UTC, SergeyGetmanskiy commented on src/contexts/RestaurantsContext.tsx
> +        if (selectedOptions.length === 0 && !isTypeSelected) {
починил

2024-03-09 09:19 UTC, SergeyGetmanskiy commented on src/contexts/RestaurantsContext.tsx
> +    const restaurantsFiltered: Restaurant[] = restaurantsOnMap.filter((restaurant) => {
починил

2024-03-11 14:51 UTC, cronon approved these changes

2024-03-11 14:58 UTC, merged