profile apimock-4fields
bronfood-com/front pull request #62
Opened 2024-03-20 17:45 UTC by olgaAsmith

без реал апи

2024-03-22 10:02 UTC, cronon requested changes

2024-03-22 10:02 UTC, cronon commented on README.md
На странице редактирования, я поменял имя. Нажал на сохранить, показывается страница 404. - должно быть что-то другое.
Я задал вопрос в фигме, какая страница должна показываться после нажатия на Сохранить. Пока не ответили, давай сделаем просто чтобы оставалась та же самая страница.

2024-03-22 13:23 UTC, olgaAsmith commented on README.md
я так поняла что хранилище временно для имитации бэка. так я бы с сервера обновила юзер инфу.

2024-03-22 14:15 UTC, cronon commented on src/pages/Profile/Profile.tsx
> +        location.reload();
local storage обновляется сразу после localStorage.setItem, можно не перезагружать

2024-03-24 12:51 UTC, olgaAsmith commented on src/pages/Profile/Profile.tsx
> +        location.reload();
Обновляет сразу локал, но у нас вот так написано в коде
useEffect(() => {
        const user = localStorage.getItem('user');
        if (user) {
            setCurrentUser(JSON.parse(user));
        }
    }, []);

2024-03-24 13:21 UTC, olgaAsmith commented on src/components/InputPhone/InputPhone.tsx
> +    //*change input
это плагин vscode который подкрашивает комменты.  просто отделяю происходящее
убрала коммент

2024-03-24 13:24 UTC, olgaAsmith commented on README.md
+

2024-03-24 13:27 UTC, olgaAsmith commented on README.md
не поняла. у меня такого не происходило.

2024-03-24 14:02 UTC, olgaAsmith commented on README.md
как я поняла из кода(может быть и не так), по обращению к запросу, мы просто делаем запрос и закидываем данные, а потом ждем код смс, потом вводим код и если совпадает то уже происходит обновление. отсюда у меня вопрос - а это там на бэке внутри этого обращения происходят все изменения, и после завершаются когда все успешно. или это вообще отдельная операция. в какой момент нужно обновлять профиль

2024-03-24 18:12 UTC, olgaAsmith commented on src/pages/Profile/Profile.tsx
> +        location.reload();
доюавила useeffect в профайл

2024-03-25 09:43 UTC, olgaAsmith commented on src/i18n.tsx
> +                            errorMessage: 'Не удалось изменить данные',
Ждем....

2024-03-25 13:46 UTC, cronon requested changes

2024-03-25 13:46 UTC, cronon commented on src/i18n.tsx
> +                            errorMessage: 'Не удалось изменить данные',
чтобы не ждать, сделай сейчас переводы по той схеме, которую ты им предложила. А если они захотят внести изменения, то потом отдельным ПРом поменяем переводы

2024-03-25 13:46 UTC, cronon commented on src/contexts/CurrentUserContext.tsx
> +            }
```suggestion
            const result = await authService.confirmRegisterPhone({ temp_data_code: res.data.temp_data_code, confirmation_code: '0000' });
            setIsLoading(false);
            if (result.status === 'error') {
                setUpdateUserErrorMessage(result.error_message);
            } else {
                setCurrentUser(result.data);
                localStorage.setItem('user', JSON.stringify(result.data));
            }
```

2024-03-25 13:46 UTC, cronon commented on src/pages/Profile/Profile.tsx
> +    const { updateUser } = useCurrentUser();
```suggestion
    const { currentUser, updateUser } = useCurrentUser();
    const [isErrorVisible, setIsErrorVisible] = useState(false);
```

2024-03-25 13:51 UTC, cronon commented on README.md
пока что интеграции с смс нет, то делаем так:
1. запрос на сервер, чтобы он обновил инфу.
2. Сервер присылает ответ, что ок,
3. Обновляем инфу на клиенте.

Когда будет интеграция с смс, то тоже самое в принципе:
1. запрос на сервер, чтобы он обновил инфу.
2. Сервер отвечает, что он отправил смс.
3. Запрос на сервер с кодом из смс
4. Сервер присылает ответ, что ок,
5. Обновляем инфу на клиенте.

То есть, когда бэк говорит, что он все обновил, тогда мы и у себя обновляем

2024-03-25 16:28 UTC, olgaAsmith commented on README.md
ок. уберу. 
зачем тогда этот код висит в signup

2024-03-27 10:00 UTC, cronon requested changes

2024-03-27 10:00 UTC, cronon commented on src/components/InputPhone/InputPhone.tsx
> +    changeValue?: () => void;
я не смог понять по этому описанию, что делает эта функция
Судя по коду, это примерно как onChange эвент у инпутов. Пусть так и будет onChange(newValue: string)

2024-03-27 10:00 UTC, cronon commented on src/contexts/CurrentUserContext.tsx
> +            setUpdateUserErrorMessage(t(`pages.error.validation`));
если например `error_message === 'Duplicate'` то сначала он поставит `setUpdateUserErrorMessage(t(`pages.error.duplicate`));` а потом вызовется `setUpdateUserErrorMessage(t(`pages.error.validation`));` и по итогу будет показывать `t(`pages.error.validation`)`

2024-03-27 10:00 UTC, cronon commented on src/pages/Profile/Profile.tsx
> +    const { updateUser } = useCurrentUser();
бамп

2024-03-27 10:00 UTC, cronon commented on src/pages/Profile/Profile.tsx
> +                <Button disabled={isButtonDisabled}>{t('pages.profile.save')}</Button>
предполагается, что пока инпут не изменялся, то эта кнопка должна быть задизаблена? Если в фигме такой функциональности нет, то надо ее убрать.

Если есть, то она у меня не работает. Я очищаю localStorage. Открываю https://bronfood-com.github.io/front/pr-preview/pr-62/ Вхожу с телефоном +7 (123) 123-12-31 пароль 1234. Открываю Редактировать личные данные. Кнопка не задизаблена

![image](https://github.com/bronfood-com/front/assets/4602009/eff28dfa-197a-4c3b-8dcc-69ac303fd075)

2024-03-27 10:00 UTC, cronon commented on src/pages/Profile/Profile.tsx
> +                <Button disabled={isButtonDisabled}>{t('pages.profile.save')}</Button>
Я очищаю localStorage. Открываю https://bronfood-com.github.io/front/pr-preview/pr-62/ Вхожу с телефоном +7 (123) 123-12-31 пароль 1234. Открываю Редактировать личные данные. Вижу Имя User. Меняю имя на User user. Нажимаю на сохранить. Ничего не происходит.

Ожидается: показывается loading indicator на 500 мс. Пока он показывается, то все кнопки и инпуты задизаблены

2024-03-27 10:00 UTC, cronon commented on src/pages/Profile/Profile.tsx
> +                <Button disabled={isButtonDisabled}>{t('pages.profile.save')}</Button>
Я очищаю localStorage. Открываю https://bronfood-com.github.io/front/pr-preview/pr-62/ Вхожу с телефоном +7 (123) 123-12-31 пароль 1234. Открываю Редактировать личные данные. Вижу Имя User. Меняю имя на User user. Нажимаю на сохранить. Ничего не происходит. Из главного меню опять открываю Редактировать личные данные. Ожидается: будет новое имя "User user" и старый телефон +7 (123) 123-12-31

Показывается другое имя и другой телефон

![image](https://github.com/bronfood-com/front/assets/4602009/575ef740-4e2d-40b8-9636-fd7d1a5461eb)

2024-03-27 10:58 UTC, olgaAsmith commented on src/pages/Profile/Profile.tsx
> +                <Button disabled={isButtonDisabled}>{t('pages.profile.save')}</Button>
юзер отсюда async login({ phone, password }: LoginData): Promise<{ status: 'success'; data: User } | { status: 'error'; error_message: string }> {
        await this._wait(500);
        if (phone && password) {
            localStorage.setItem('token', '23423434');
            return { status: 'success', data: { fullname: 'User', phone, role: 'CLIENT' } };
        } else {
            return { status: 'error', error_message: 'invalidCredentials' };
        }
    } 

превью прошлый, этот не знаю, это не он. ошибок не обозначил, галочки тоже нет

2024-03-27 10:59 UTC, olgaAsmith commented on src/pages/Profile/Profile.tsx
> +                <Button disabled={isButtonDisabled}>{t('pages.profile.save')}</Button>
ок, пусть отправляют тоже самое что уже есть

2024-03-27 11:01 UTC, olgaAsmith commented on src/pages/Profile/Profile.tsx
> +    const { updateUser } = useCurrentUser();
что это

2024-03-27 11:09 UTC, olgaAsmith commented on src/contexts/CurrentUserContext.tsx
> +            setUpdateUserErrorMessage(t(`pages.error.validation`));
лишняя строка

2024-03-27 11:10 UTC, olgaAsmith commented on src/pages/Profile/Profile.tsx
> +                <Button disabled={isButtonDisabled}>{t('pages.profile.save')}</Button>
теперь крутит

2024-03-27 13:14 UTC, cronon commented on src/pages/Profile/Profile.tsx
> +    const { updateUser } = useCurrentUser();
обращаю внимание на свой коммент. Я хочу, чтобы код был такой, как я предлагаю. Ты согласна с таким предложением?

2024-03-27 13:53 UTC, olgaAsmith commented on src/contexts/CurrentUserContext.tsx
> +            }
схему передам

2024-03-27 13:55 UTC, olgaAsmith commented on src/components/InputPhone/InputPhone.tsx
> +    changeValue?: () => void;
убрано

2024-03-27 19:15 UTC, cronon approved these changes

2024-03-28 09:34 UTC, merged