add sms screen/+routes
bronfood-com/front pull request #70
Opened 2024-04-01 13:31 UTC by olgaAsmith

окно с инпутом пин-код (react-input-pin-code) + роуты к нему

2024-04-01 14:48 UTC, cronon requested changes

2024-04-01 14:48 UTC, cronon commented on src/i18n.tsx
> +                        },
названия ключей должны быть такие, чтобы видя только их, можно было понять о чем это. Когда будем переводить на казахский и забудем что-то перевести, то хотя бы будет возможность понять что там было в оригинале.
```suggestion
                            phoneConfirmation: 'Подтверждение номера',
                            enterSmsCode: 'Ввведите код из смс',
                        },
```
Да и в jsx-коде с такими ключами понятнее, что юзер видит на странице

2024-04-01 14:48 UTC, cronon commented on src/pages/SMSConfirm/SMSConfirm.tsx
> +    const onSubmit = () => {};
пускай лучше это будет дефолтным значением для компонента Form

2024-04-01 14:48 UTC, cronon commented on package.json
В рамках какого тикета эта работа и что ты планируешь делать дальше?
Просто так если это смержить, то будет нерабочая вещь. Когда я нажимаю на Далее, то меня перенаправляет на страницу 404.
Нужно сделать полный путь для какого-нибудь места, где требуется смс-подтверждение. Если два человека хотят работать одновременно над ними, тогда смержим только верстку попапа с смс, без роутов

2024-04-01 14:48 UTC, cronon commented on src/pages/SMSConfirm/SMSConfirm.tsx
> +    const handleComplete = (values: string[]) => {
зачем нужна эта функция?

2024-04-01 14:48 UTC, cronon commented on package.json
> +    "styled-components": "^6.1.8",
для чего нужны styled-compnents? Если не нужны, то надо удалить и перегенерировать package-lock

2024-04-01 14:48 UTC, cronon commented on src/App.tsx
> +                <Route path="/confirmation" element={<ProtectedRoute component={<SMSConfirm />} />} />
Каждый из таких попапов должен много знать о том, откуда он вызывается: на какой эндпоинт нужно сделать запрос, и на какую страницу вернуться. Через один роут это будет очень сложно. Лучше или через вложенные роуты, например, /profile/confirmation. Или без роутов внутри соответственных страниц заводить стейт и по условию показывать SMSConfirm

2024-04-04 14:02 UTC, olgaAsmith commented on src/i18n.tsx
> +                        },
++

2024-04-04 14:04 UTC, olgaAsmith commented on package.json
+ еще будет апи

2024-04-04 14:04 UTC, olgaAsmith commented on src/pages/SMSConfirm/SMSConfirm.tsx
> +    const onSubmit = () => {};
++

2024-04-04 14:05 UTC, olgaAsmith commented on src/pages/SMSConfirm/SMSConfirm.tsx
> +    const handleComplete = (values: string[]) => {
по заврешении набора цифр в инпуты создает массив из введенных цифр. 
функция плагина

2024-04-04 14:08 UTC, olgaAsmith commented on package.json
> +    "styled-components": "^6.1.8",
++

2024-04-04 15:19 UTC, olgaAsmith commented on src/App.tsx
> +                <Route path="/confirmation" element={<ProtectedRoute component={<SMSConfirm />} />} />
создала компонент внутри

2024-04-04 18:42 UTC, cronon commented on src/components/SMSConfirm/SMSConfirm.tsx
> +    parentPage: 'signup' | 'profile';
это антипаттерн, когда компонент знает на какой странице он находится. 

Получается, что поведение, уникальное для signup страницы описано в файле SMSConfirm. И переплетается с поведением, уникальным для profile.

Надо делать или так, чтобы функциональность, разная для разных страниц, оставалась в файлах самих страниц.

Через чилдренов например. Или реюзабельный компонент сам сделать поменьше, или вообще от него отказаться.

Моя быстрая интуиция предлагает такое использование этого попапа на странице signup:
`isSMSConfirmOpen && <SMSConfirm isLoading={confirmSignUp.isLoading} error={confirmSignUp.error} onSubmit={code => await confirmSignUp.mutation(code); setIsSMSConfirmOpen(false); navigate('/'); } />`

2024-04-04 18:42 UTC, cronon commented on src/contexts/CurrentUserContext.tsx
> +        mutation: (data: FieldValues) => Promise<void | string | undefined>;
в каких случаях может быть string или undefined? Судя по коду там только void

2024-04-04 18:42 UTC, cronon commented on src/pages/Profile/Profile.tsx
> +                <SMSConfirm parentPage="profile"></SMSConfirm>
После подтверждения кода для обновления профиля, должно возвращаться на страницу профиля. Сейчас перекидывает на главную страницу

2024-04-09 19:42 UTC, olgaAsmith commented on src/components/SMSConfirm/SMSConfirm.tsx
> +    parentPage: 'signup' | 'profile';
ок. прокидывание через пропсы

2024-04-09 19:43 UTC, olgaAsmith commented on src/pages/Profile/Profile.tsx
> +                <SMSConfirm parentPage="profile"></SMSConfirm>
++

2024-04-10 14:15 UTC, cronon requested changes

2024-04-10 14:15 UTC, cronon commented on src/pages/Profile/Profile.tsx
> +        if (result !== null) {
но результат всегда undefined здесь и условие никогда не будет true

2024-04-10 14:15 UTC, cronon commented on src/pages/Profile/Profile.tsx
> +        setIsConfirmOpen(false);
а если условие и будет true, то юзер не увидит ошибки, потому, что попап спрячется

2024-04-10 14:15 UTC, cronon commented on package.json
Регистрируюсь, пишу имя "фыва фыва". Номер телефона +71231231231, пароль. Потом ввожу 1234 как код подтверждения из смс. Нажимаю Далее, показывается попап Спасибо за регистрацию. Потом он пропадает, и я вижу карту и список ресторанов. Захожу на Редактировать личные данные
Ожидаю: имя "фыва фыва", номер телефона +71231231231 
Происходит: имя "user registred", номер телефона +74443332211

![image](https://github.com/bronfood-com/front/assets/4602009/bac42faf-ca94-4810-a408-f9ab972c824e)

Если поменять личные данные, то они тоже не сохраняются

2024-04-10 14:15 UTC, cronon commented on package.json
Я правильно понял, что в этом ПРе у тебя в том числе и изменение пароля должно быть? Сейчас в форме обязательно нужно ввести пароль. В конце-концов надо сделать так, чтобы было необязательно вводить пароль. Можно или сейчас убрать эти поля и добавить потом, или сделать сейчас, чтобы они были необязательные.

2024-04-11 12:34 UTC, olgaAsmith commented on src/components/SMSConfirm/SMSConfirm.tsx
> +    getCode: (arg: string) => void;
точно. спасибо

2024-04-11 12:35 UTC, olgaAsmith commented on src/components/SMSConfirm/SMSConfirm.tsx
> +     * Submit function
++

2024-04-11 15:33 UTC, olgaAsmith commented on src/contexts/CurrentUserContext.tsx
> +        mutation: (data: FieldValues) => Promise<string | undefined>;
![Скриншот 11-04-2024 183130](https://github.com/bronfood-com/front/assets/116520024/d8f3ce4d-d06d-49fc-9895-de9e905041bf)
тс мне ошибку помечает

2024-04-11 15:37 UTC, olgaAsmith commented on src/contexts/CurrentUserContext.tsx
> +            return;
это тут так было. логаут не трогала.
но иф убираю тогда

2024-04-11 15:43 UTC, olgaAsmith commented on package.json
это норм. т.к. при отправке смс кода получаем от сервера ответ в виде юзера, и инфа записывается в юзера. соотв на мок я возвращаю данные вручную. и они записываются в локал. 
![Скриншот 11-04-2024 184208](https://github.com/bronfood-com/front/assets/116520024/0907a172-bdbe-4eb4-866f-e6765a18d131)

2024-04-11 15:44 UTC, olgaAsmith commented on package.json
а как это сделать, если сам запрос на сервер ждет пароль?

2024-04-11 15:52 UTC, olgaAsmith commented on src/contexts/CurrentUserContext.tsx
> +        mutation: (data: FieldValues) => Promise<string | undefined>;
добавляю return null;

2024-04-11 17:14 UTC, olgaAsmith commented on src/pages/Profile/Profile.tsx
> +        if (result !== null) {
пропишу return

2024-04-12 11:44 UTC, cronon commented on package.json
я хотел сначала попросить сделать, чтобы мок запоминал, какой юзер в него приходил, чтобы нам не думать, баг здесь или нет. Потом подумал, что в таком случае появятся разные эдж-кейсы, и надо будет всю бэковую логику по сути здесь имплементировать.
Пускай будет как сейчас

2024-04-12 11:49 UTC, cronon commented on package.json
тогда попроси у бэков чтобы сделали пароль необязательный

В любом случае надо сделать, чтобы валидация и моки у нас не требоволи обязательный пароль. Если бэки к тому моменту свои изменения не сделают, то оставляй все на моках, и мержи этот ПР. И для интеграции с бэком сделай отдельный тикет - когда бэки готовы будут, тогда заинтегрируем

2024-04-14 13:16 UTC, olgaAsmith commented on package.json
ок

2024-04-14 13:16 UTC, olgaAsmith commented on package.json
ок

2024-04-16 09:42 UTC, cronon approved these changes

2024-04-16 15:32 UTC, merged