WaitingConfirmOrderModal, WaitingOrderModal and UI's element ProgressBar added
bronfood-com/front pull request #71
Opened 2024-04-02 07:19 UTC by mityourik

Выполнены два модальных окна:
1) (Роут '/waiting-confirm-order') Ожидание подтверждения заказа со шкалой прогресса на 3 минуты (при ожидании этого подтверждения происходит запрос через confirmOrderThunk, в котором симулируется запрос к серверу с задержкой в 2 секунды, и при получении успешного ответа, пользователь перенаправляется на роут 'waiting-order')
2) (Роут '/waiting-order') Ожидание подготовки заказа. Если нажать на отмену заказа, то идет перенаправление на попап подтверждения действия ('/waiting-order'). Во время нахождения там, счетчик подготовки заказа и счетчик времени отмены заказа не сбрасываются.

2024-04-02 10:14 UTC, cronon requested changes

2024-04-03 11:32 UTC, mityourik commented on src/components/OrderTimeCounter/OrderTimeCounter.tsx
> +        return 'components.orderTimeCounter.delayed';
т.е. запрос который периодично опрашивает сервер о статусе заказа в процентах и их подставлять в состояние шкалы прогресса?

2024-04-04 14:45 UTC, cronon commented on src/components/OrderTimeCounter/OrderTimeCounter.tsx
> +        return 'components.orderTimeCounter.delayed';
и о статусе заказа в процентах тоже, если есть такая возможность. Но я думаю у них будет только информация о приблизительном времени когда будет готово.

Но в том комменте я в первую очередь имею в виду статусы: "готовится" "готов" "задерживается"

2024-04-16 12:09 UTC, cronon commented on index.html
Нужно ответить на все комменты, даже если это выглядит тупо "сделано, сделано, сделано". Но так очень легко мне видно, куда теперь смотреть и понятно, что все сделано. А тебе таким образом будет тяжело что-то пропустить

2024-04-16 12:09 UTC, cronon commented on package.json
> +    "husky": "^9.0.11",
была ли какая-нибудь проблема со старым хаски? Если не была, то надо откатить и packge.json и package-lock

2024-04-16 12:09 UTC, cronon commented on index.html
как попасть на страницу ожидания в превью билде?

2024-04-16 12:09 UTC, cronon commented on src/App.tsx
> +import { Route, Routes, useLocation, useNavigate } from 'react-router-dom';
не делай лишних изменений. Так тяжелее ревьювать, а время тратится в никуда. Плюс, как-нибудь оно выстрелит тебе в ногу и придется решать чужие баги. Ты думал поменяешь импорты местами и ничего не случится, а там все сломалось, и надо разбираться. Думал за день таску закроешь, а уехал на неделю. (Пишу из своего опыта :) )

2024-04-16 12:09 UTC, cronon commented on src/components/OrderListArticle/OrderListArticle.tsx
> +const OrderListArticle1: FC<OrderListArticleProps> = ({ order }) => {
Этот компонент используется только в WaitingOrder, поэтому нужно положить его в pages

2024-04-17 12:35 UTC, mityourik commented on package.json
> +    "react-redux": "^9.1.0",
удален с тулкитом. Сделал через конекст

2024-04-17 12:35 UTC, mityourik commented on package.json
> +    "husky": "^9.0.11",
done

2024-04-17 12:36 UTC, mityourik commented on package.json
> +    "eslint": "^8.57.0",
откатил

2024-04-17 12:36 UTC, mityourik commented on src/App.tsx
> +                            throw new Error('функция сабмита не реализована, но нужно отправить запрос на сервер через Redux');
done

2024-04-17 12:38 UTC, mityourik commented on src/App.tsx
> +                        children={undefined}
это я сделал потому не стал изменять чужой компонент. Там был он обязательным, но я подправил на необязательный

2024-04-17 12:39 UTC, mityourik commented on src/UI/ProgressBar/ProgressBar.tsx
сделано

2024-04-17 12:43 UTC, mityourik commented on src/UI/ProgressBar/ProgressBar.tsx
> +                requestAnimationFrame(updateProgress);
сделал обновление раз в минуту. По поводу времени ожидания: сделал в контракте поле, в котором должно приходить общее время приготовления заказа.

2024-04-17 12:43 UTC, mityourik commented on src/components/OrderListArticle/OrderListArticle.tsx
> +import { IOrder } from "../../interfaces/order";
исправлено

2024-04-17 12:47 UTC, mityourik commented on src/components/OrderTimeCounter/OrderTimeCounter.tsx
> +        return 'components.orderTimeCounter.delayed';
вообще из логики макета ясно, что предполагается общее расчетное время и затем его превышение если статус заказа не изменился. В моей версии контракта есть поле: confirmationStatus: 'waiting' | 'confirmed' | 'notConfirmed';

2024-04-17 12:48 UTC, mityourik commented on src/components/OrderTimeCounter/OrderTimeCounter.tsx
> +    }, [remainingTime, t]);
исправлено.

2024-04-17 12:48 UTC, mityourik commented on src/components/OrderTimeCounter/OrderTimeCounter.tsx
> +    }), [remainingTime]);
исправлено

2024-04-17 12:49 UTC, mityourik commented on src/components/Popups/ConfirmationPopup/ConfirmPopup.module.scss
> +    position: fixed;
вернул в relative

2024-04-17 12:49 UTC, mityourik commented on src/components/WaitingOrderModal/WaitingOrderModal.tsx
> +                </p>
убрал это совсем

2024-04-17 12:50 UTC, mityourik commented on src/i18n.tsx
> +                            subtitle: 'Приготовление начнётся с момента подтверждения',
выполнено

2024-04-17 12:51 UTC, mityourik commented on src/interfaces/order.ts
положил в папку .../utils/api/orderService/orderService.ts

2024-04-17 13:04 UTC, mityourik commented on src/styles/variables.scss
> +$grey-subtitle: #7A7575;
запрошено в макете

2024-04-17 13:04 UTC, mityourik commented on src/utils/hooks/useCountdown/useCountdown.ts
> +export const useCountdown = (estimatedTime: number) => {
удален

2024-04-18 14:00 UTC, mityourik commented on orderDb.json
done

2024-04-18 14:01 UTC, mityourik commented on orderDb.json
> +      "orderDetails": [
надо уточнить. не понимаю что конкретно не так)

2024-04-18 14:01 UTC, mityourik commented on package.json
> +    "husky": "^9.0.11",
откачено

2024-04-18 14:09 UTC, mityourik commented on src/App.tsx
> +import { Route, Routes, useLocation, useNavigate } from 'react-router-dom';
как-то случайно вышло. Спасиб за совет!

2024-04-20 04:54 UTC, mityourik commented on index.html
возможно что я не понял вопроса, но отвечу: попасть на страницу ожидания можно по роуту /waiting-order

2024-04-22 09:45 UTC, cronon commented on index.html
Превью билд, это деплой твоего бранча на gh-pages - каждый ПР автоматически деплоится, и выдается ссылка. У тебя это
https://bronfood-com.github.io/front/pr-preview/pr-71/

![image](https://github.com/bronfood-com/front/assets/4602009/749eea1a-42a9-41d0-a6a0-ab4a95b36ca1)

Надо сделать, чтобы в этом превью можно было увидеть страницу ожидания. Если я руками поменяю путь на https://bronfood-com.github.io/waiting-order то показывает 404 страницу.
В корзине у нас уже есть кнопка Оплатить - пускай по нажатию на нее переходит на страницу Waiting.

2024-04-22 09:54 UTC, cronon commented on src/interfaces/order.ts
1. Где можно посмотреть на контракт, который ты бэкам отправлял?
2. Или можно так сделать: добавь свои предложения в ноушен и выдели как-то, что это еще предложения. Типа *Эти изменения не были приняты. Ждем апрува от бэка* Когда бэки апрувнут, то эту надпись уберешь. Так у нас всегда под рукой будет ссылка, которую при случае можно будет показать всем заинтересованным
3. Когда бэки апрувнут?

2024-04-22 10:54 UTC, cronon requested changes

2024-04-22 10:54 UTC, cronon commented on src/components/OrderListArticle/OrderListArticle.tsx
> +const OrderListArticle1: FC<OrderListArticleProps> = ({ order }) => {
![image](https://github.com/bronfood-com/front/assets/4602009/993f96a4-16ad-493a-8026-1a4c877da174)
Похоже ты не запушил

2024-04-22 10:54 UTC, cronon commented on src/UI/ProgressBar/ProgressBar.tsx
> +                requestAnimationFrame(updateProgress);
Как кастомер и бэки отвечают на этот вопрос "вот юзер сделал заказ и мы показали ему время ожидания 10 минут. Прошло 10 минут. Значит ли теперь, что мы показываем, что заказ готов, безотносительно как оно на самом деле? Или админ заведения должен у себя нажать на кнопку, и только тогда юзеру покажется, что заказ готов?" ?

2024-04-22 10:54 UTC, cronon commented on src/components/OrderTimeCounter/OrderTimeCounter.tsx
> +    const getStatusMessage = remainingTime > 0 ? 'components.orderTimeCounter.yourOrderIsAlreadyBeingPrepared' : remainingTime === 0 ? 'components.orderTimeCounter.yourOrderIsReady' : 'components.ord
>  В моей версии контракта есть поле: confirmationStatus: 'waiting' | 'confirmed' | 'notConfirmed';

Тогда надо брать сообщение из confirmationStatus, а не вычислять его самому

2024-04-22 10:54 UTC, cronon commented on src/components/Popups/ConfirmationPopup/ConfirmationPopup.tsx
> +    onSubmit: () => void | Promise<void>; // может быть и асинхронной // Орлов Дима
```suggestion
    onSubmit: () => void;
```
Так будет ошибка какая-то? void по идее включает в себя любой тип, в том числе и промис

2024-04-22 10:54 UTC, cronon commented on src/components/Popups/ConfirmationPopup/ConfirmationPopup.tsx
> +    children?: ReactNode; // сделал необязательным // Орлов Дима
1. Комменты должны быть только на английском
2. 3. эти комменты надо удалить, они повторяют то, что написано в коде. Я вижу вопросительный знак у children? и понимаю, что это необязательное поле. Об этом не нужно говорить дополнительно
3. комменты с авторством тоже надо удалить - кто захочет узнать автора, сделает это через историю гита

2024-04-22 10:54 UTC, cronon commented on src/components/Popups/ConfirmationPopup/ConfirmationPopup.tsx
> +        }
эту вещь надо оставить на совести того, кто использует ConfirmationPopup. Пусть остается только onSubmit, а onSuccess надо убрать

Если я делаю асинхронную функцию onSubmit, то я знаю как работают промисы и я смогу сам написать then, и я не буду для этого дополнительно изучать как работает ConfirmationPopup

2024-04-22 10:54 UTC, cronon commented on src/components/ProgressBar/ProgressBar.tsx
> +    currentTime: number;
добавь им пожалуйста jsdoc. Я изначально воспринял эти числа как юникс-время, но судя по коду там что-то другое должно быть, но я не могу понять что

2024-04-22 10:54 UTC, cronon commented on src/i18n.tsx
> +                            minutes: 'минут',
Сделай пожалуйста отдельный тикет чтобы добавить склонения к минутам (1 минута, 2 минуты, 5 минут)
https://www.i18next.com/translation-function/plurals
С этим надо хорошо разобраться, но это не супер критичный баг будет если мы покажем "1 минут"

Прикрепи в тикете ссылку к этому комменту. И в комменте оставь ссылку на тикет. Чтобы тому, кто возьмет тикет была доступна вся инфа и весь контекст

2024-04-22 10:54 UTC, cronon commented on src/pages/WaitingOrder/WaitingOrder.tsx
> +    const WAIT_CODE_IN_SECONDS = 5 * 60; // секунды для ожидания кода заказа (запросить у бэка)
самое время тебе запросить)

2024-04-22 10:54 UTC, cronon commented on src/pages/WaitingOrder/WaitingOrder.tsx
> +                        <img src={waitingImg} alt="waiting image" className={styles.waitingOrder__img} />
1. Вообще, alt нужно брать из i18n, к alt и aria- атрибутам надо отностится как будто это такие же надписи на экране, как и остальные
2. Зрячий человек не получит новой информации о статусе заказа когда он увидит эту картинку - надпись "ждем заказ" он уже прочитал, Слепой тоже прочитал при помощи скринридера надпись "ждем заказа" и не зачем ему читать эту же надпись еще раз. Еще хуже дела обстоят на других страницах: надпись говорит, что заказ отменен, а картинка говорит, что заказ ожидается. - Все это говорит, что картинка не несет информативной ценности, а нужна только как элемент оформления. Такие картинки надо делать через background-image на диве или спане - скринридеры и поисковые роботы их проигнорируют

Итого: здесь и в других попапах waiting image не должен быть img, а должен ставиться через background-image

2024-04-22 10:54 UTC, cronon commented on src/pages/WaitingOrder/WaitingOrder.tsx
> +        try {
Не юзайте try/catch
https://telegra.ph/Ne-yuzajte-try-catch-throw-esli-mozhno-bez-ehtogo-12-15

Надо сделать чтобы из useOrderContext выходил объект например 
```
cancelOrder: {
  mutation: (orderId: string) => Promise<void>
  isLoading: boolean;
  error: string | null
}
```
а сетаться isLoading и error будут внутри контекста. Компонент будет только решать что показывать когда ошибка и когда лоадинг, в таком духе:
```
<>
  {isLoading && loading-indicator}
  {error && <div color=red>{t('components.waitingOrder.'+ error)}</div>
  <button onClick={() => mutation(orderId).then(() => navigate('/')}>Yes</button
</>
````
У нас так уже сделаны рестораны, корзина и currentUser

2024-04-22 10:54 UTC, cronon commented on src/pages/WaitingOrderPage/WaitingOrderPage.tsx
> +            <OrderProvider clientId="clientId1">
мы говорим userId (хотя это не точно). Точно, что надо брать его из контекста с currentUser

2024-04-22 10:54 UTC, cronon commented on src/utils/api/orderApiRequests/orderApi.ts
> +const baseUrl = 'http://localhost:3001';
baseUrl у нас уже был где-то, надо юзать один для всех сервисов

2024-04-22 10:54 UTC, cronon commented on src/utils/api/orderApiRequests/orderApi.ts
посмотри как сделаны остальные сервисы
Мы называем их например restaurantService/restaurantServiceMock и restaurantServiceReal

2024-04-22 10:54 UTC, cronon commented on src/utils/api/orderApiRequests/orderApi.ts
> +        if (!response.ok) {
так не получится, это каждый конкретный путь должен сам решать, какая не-ок ситуация соответствует какой ошибке
Вообще мы эти моменты с бэками обговариваем. Например я знаю, что при регистрации юзера может быть, что такой телефон уже занят, поэтому мы  с бэками договорились, что должны они в таких случаях присылать ключ типа 'UserIsAlreadyRegistered'. А потом мы через i18n показываем это сообщение на нужном языке

2024-04-22 10:54 UTC, cronon commented on src/utils/api/orderApiRequests/orderApi.ts
> +    } catch (error) {
а от этого не убежать потому, что fetch делает исключение, когда нет интернета. Соответственно здесь дальше должно быть не просто 'An unexpected error', а ключ 'NetworkError'

Создай пожалуйста тикет "Учесть networkError для реальных сервисов". Когда ты смержишь этот ПР, то функцию fetchResponse потом применим к остальным реальным сервисам

2024-04-22 10:54 UTC, cronon commented on src/utils/api/orderApiRequests/orderApi.ts
> +export const fetchOrderIdByClientId = async (clientId: string): Promise<ApiResponse<string>> => {
эти методы должны быть в классе

2024-04-22 10:54 UTC, cronon commented on src/utils/api/orderApiRequests/orderApi.ts
> +    if (response.error || response.data === null || response.data.length === 0) {
Как может быть такое, что response.error === false, и response.data === null? Если никак, то не надо это учитывать, и надо оставить только одну проверку.

2024-04-22 10:54 UTC, cronon commented on src/utils/api/orderService/orderService.ts
> + * @property {number} quantity - Number of units of the item ordered.
эти штучки надо писать над каждым полем в интерфейсе

2024-04-22 10:54 UTC, cronon commented on src/utils/api/orderService/orderService.ts
> +    confirmationStatus: string;
в этом и остальных таких местах - это не просто string, а т.н. union string
`confirmationStatus: 'waiting' | 'confirmed' | 'notConfirmed';`

2024-04-22 10:54 UTC, cronon commented on src/utils/hooks/useTimer/useTimer.ts
> +            setPreparationTime((prevTime) => prevTime - 1);
лучше вычислять это из Date.now(), будет точнее. Потому, что если я переключу вкладку, или Андроид выключит мне браузер, пока я в телефоне перейду в другое приложение, то скорее всего setInterval не будет выполняться. И когда я открою вкладку через 10 минут, то будет показываться, что прошло 0 минут

2024-04-22 10:54 UTC, cronon commented on src/utils/hooks/useTimer/useTimer.ts
> +export const useTimers = ({ setPreparationTime, setWaitOrderCodeTime, setCancellationCountdown }: UseTimerProps) => {
добавь плз jsdoc'и к useTimers и UseTimerProps. Я не смог быстро понять, что эти штуки делают

2024-04-24 06:07 UTC, mityourik commented on src/UI/ProgressBar/ProgressBar.tsx
> +                requestAnimationFrame(updateProgress);
задал вопрос в чатике бэка. По результату отпишусь в наш чат. Записал также этот вопрос в свой тикет

2024-04-24 06:11 UTC, mityourik commented on src/interfaces/order.ts
1. Проект контракта тут: https://www.notion.so/API-Restaurant-Meal-Basket-Order-e7947e0efa5948238032620646f28890?pvs=4#9e39e3ff05504b4bafdeb65f741c6c28
2. Сделано
3. Отпишусь как ответят

2024-04-24 07:49 UTC, mityourik commented on index.html
сделан навигейт на /waiting-order при клике на "Оплатить" в корзине

2024-04-24 08:12 UTC, mityourik commented on src/components/OrderListArticle/OrderListArticle.tsx
> +const OrderListArticle1: FC<OrderListArticleProps> = ({ order }) => {
не перенес. Теперь ок

2024-04-24 08:37 UTC, mityourik commented on .husky/pre-commit
у меня ругался терминал на хаски и я его переустановил ту же версию. А команду chmod +x .husky/pre-commit сделал чтобы хук запустился, так как после переустановки не происходили проверки

2024-04-24 08:43 UTC, mityourik commented on src/components/Modal/Modal.tsx
> +const Modal: FC<ModalProps> = ({ children }) => {
единственная разница, это крестик для закрытия окна. В модале его нет.
А остальные стили я скопипастил с попапа

2024-04-24 08:49 UTC, mityourik commented on src/components/OrderTimeCounter/OrderTimeCounter.tsx
> +    const getStatusMessage = remainingTime > 0 ? 'components.orderTimeCounter.yourOrderIsAlreadyBeingPrepared' : remainingTime === 0 ? 'components.orderTimeCounter.yourOrderIsReady' : 'components.ord
А ведь все равно надо показывать шкалу прогресса ожидания заказа. Я ведь беру PreparationTime от сервера и запускаю таймер. Затем, опрашиваю регулярно сервер про этот статус (это еще не реализовано у меня кстати) и если готово, то показываю пользователю

2024-04-24 15:41 UTC, mityourik commented on src/components/Popups/ConfirmationPopup/ConfirmationPopup.tsx
> +    onSubmit: () => void | Promise<void>; // может быть и асинхронной // Орлов Дима
Да. При использовании промиса на этот колбэк линтер ругается

2024-04-24 15:41 UTC, mityourik commented on src/components/Popups/ConfirmationPopup/ConfirmationPopup.tsx
> +    children?: ReactNode; // сделал необязательным // Орлов Дима
комменты удалены

2024-04-24 21:21 UTC, mityourik commented on src/components/Popups/ConfirmationPopup/ConfirmationPopup.tsx
> +        }
убрал это из ConfirmationPopup.

2024-04-24 21:33 UTC, mityourik commented on src/components/ProgressBar/ProgressBar.tsx
> +    currentTime: number;
сделано

2024-04-24 21:55 UTC, mityourik commented on src/i18n.tsx
> +                            minutes: 'минут',
тикет создал: https://github.com/orgs/bronfood-com/projects/1/views/1?pane=issue&itemId=60914548

2024-04-24 21:56 UTC, mityourik commented on src/pages/WaitingOrder/WaitingOrder.tsx
> +    const WAIT_CODE_IN_SECONDS = 5 * 60; // секунды для ожидания кода заказа (запросить у бэка)
да уж. Соррис что долго. Запросил в итоге. Завтра буду разбираться с ответом бэка

2024-04-25 05:11 UTC, mityourik commented on src/pages/WaitingOrder/WaitingOrder.tsx
> +                        <img src={waitingImg} alt="waiting image" className={styles.waitingOrder__img} />
исправлено. Спасибо за классное объяснение!

2024-04-25 08:04 UTC, mityourik commented on src/pages/WaitingOrder/WaitingOrder.tsx
> +        try {
я сделал, но не понимаю нужно ли показывать ошибку запроса или ожидания юзеру. (в макете такого не нашел)

2024-04-25 08:24 UTC, mityourik commented on src/pages/WaitingOrderPage/WaitingOrderPage.tsx
> +            <OrderProvider clientId="clientId1">
в нашем CurrentUserContext пока нет поля userId. Значит ли это, что мне надо его добавить туда, или создать тикет?

2024-04-29 15:13 UTC, olgaAsmith commented on src/i18n.tsx
> +                            minutes: 'минут',
> тикет создал: https://github.com/orgs/bronfood-com/projects/1/views/1?pane=issue&itemId=60914548

извиняюсь, т.к. ветки нет в мэин, то наверное проще будет тебе добавить несколько строк

const howMuch = number % 10 === 1 && number % 100 !== 11 ? 'one' : [2, 3, 4].includes(number % 10) && ![12, 13, 14].includes(number % 100) ? 'few' : 'many'; // возвращает one two many в зависимости от числа ( если правильно поняла, то number --> cancellationCountdown)

<p> {number} {t('components.waitingOrder.minutes_' + howMuch)} <p>
// в текст пишем число минут и собираем конкатенацией


//это в файл i18n
       minutes_one: 'минута',
       minutes_few: 'минуты',
       minutes_many: 'минут',

2024-05-01 13:28 UTC, cronon commented on src/components/OrderTimeCounter/OrderTimeCounter.tsx
> +    const getStatusMessage = remainingTime > 0 ? 'components.orderTimeCounter.yourOrderIsAlreadyBeingPrepared' : remainingTime === 0 ? 'components.orderTimeCounter.yourOrderIsReady' : 'components.ord
шкалу - да, а statusMessage надо брать из confirmationStatus, а не вычислять его самому

2024-05-01 13:31 UTC, cronon commented on src/pages/WaitingOrder/WaitingOrder.tsx
> +        try {
спроси тогда это у дизайнеров. Чтобы уменьшить вероятность того, что дизайнер в ответ нарисует что-то сложное, ты можешь предварительно сделать у себя по-простому, например див с красными буквами, и скриншот приложить к своему вопросу "я сделал, что ошибка показывается так. Вы согласны?". В таком случае 99% вероятность, что будут согласны. Для маленьких уточнений в дизайне это все так работает

2024-05-01 13:33 UTC, cronon commented on src/pages/WaitingOrderPage/WaitingOrderPage.tsx
> +            <OrderProvider clientId="clientId1">
Надо тебе самому "пролоббировать" его у бэков и добавить к нам.

2024-05-01 13:35 UTC, cronon commented on src/i18n.tsx
> +                            minutes: 'минут',
@olgaAsmith спасибо за инициативу
Ты можешь сделать свою ветку от ветки feature/waiting-screen-user и создать ПР в нее

2024-05-02 11:24 UTC, mityourik commented on src/pages/WaitingOrder/WaitingOrder.tsx
> +        try {
В случае ошибки можно отрендеривать вместо компонента OrderTimeCounter вот такое: (*
<img width="373" alt="Screenshot 2024-05-02 at 2 16 41 PM" src="https://github.com/bronfood-com/front/assets/124420137/a039cbb9-a724-4711-9b02-2a25e0a8677b">
скрин)

2024-05-03 09:05 UTC, mityourik commented on src/utils/api/orderService/orderService.ts
> + * @property {number} quantity - Number of units of the item ordered.
выполнено

2024-05-03 19:36 UTC, mityourik commented on src/utils/api/orderApiRequests/orderApi.ts
> +        if (!response.ok) {
исправлено

2024-05-03 19:40 UTC, mityourik commented on src/utils/api/orderApiRequests/orderApi.ts
> +    } catch (error) {
создал тикет https://github.com/orgs/bronfood-com/projects/1/views/1?pane=issue&itemId=61838418

2024-05-03 19:40 UTC, mityourik commented on src/utils/api/orderApiRequests/orderApi.ts
> +export const fetchOrderIdByClientId = async (clientId: string): Promise<ApiResponse<string>> => {
сделано

2024-05-03 20:02 UTC, mityourik commented on src/utils/api/orderApiRequests/orderApi.ts
> +    if (response.error || response.data === null || response.data.length === 0) {
убрал

2024-05-03 20:02 UTC, mityourik commented on src/utils/api/orderService/orderService.ts
> +    confirmationStatus: string;
да. исправил

2024-05-04 11:15 UTC, mityourik commented on src/utils/hooks/useTimer/useTimer.ts
> +            setPreparationTime((prevTime) => prevTime - 1);
сделал

2024-05-04 11:30 UTC, mityourik commented on src/utils/hooks/useTimer/useTimer.ts
> +export const useTimers = ({ setPreparationTime, setWaitOrderCodeTime, setCancellationCountdown }: UseTimerProps) => {
добавлен jsdoc сюда

2024-05-05 07:11 UTC, mityourik commented on src/components/Modal/Modal.tsx
> +const Modal: FC<ModalProps> = ({ children }) => {
@cronon в итоге нужно ли модал сделать попапом?

2024-05-05 18:02 UTC, SergeyGetmanskiy requested changes

2024-05-05 20:29 UTC, mityourik commented on src/components/Popups/ConfirmationPopup/ConfirmPopup.module.scss
> +    transform: translate(-50%);
ты прав! Вернул как было и сделал стили своей обертке которая центрирует ConfirmPopup.

2024-05-06 09:47 UTC, cronon commented on src/UI/ProgressBar/ProgressBar.tsx
> +                requestAnimationFrame(updateProgress);
Есть ли результаты? Если нет - создай отдельный тикет плз для этого вопроса, чтобы мы не забыли про него

2024-05-06 09:50 UTC, cronon commented on src/components/Modal/Modal.tsx
> +const Modal: FC<ModalProps> = ({ children }) => {
Сложный вопрос, я бы сделал в попапе опцию "показывать или не показывать крестик", но это может занять время и на текущий момент это скорее вкусовая штука, а не что-то что реальные проблемы делает. Сделай плз тикет для этого отдельный

2024-05-06 10:33 UTC, cronon requested changes

2024-05-06 10:33 UTC, cronon commented on src/pages/WaitingOrderPage/WaitingOrder/WaitingOrder.tsx
> +    const WAIT_CODE_IN_SECONDS = 5 * 60; // секунды для ожидания кода заказа (запросить у бэка)
что значит запросить у бэка?

2024-05-06 10:33 UTC, cronon commented on src/pages/WaitingOrderPage/WaitingOrder/WaitingOrder.tsx
> +    useEsc(() => setShowConfirmationPopup(false), [showConfirmationPopup]);
```suggestion
    useEsc(() => setShowConfirmationPopup(false), [setShowConfirmationPopup]);
```

2024-05-06 10:33 UTC, cronon commented on src/utils/api/orderService/orderService.ts
> +    id: string;
```suggestion
    /** 
     * Meal's id
     */
    id: string;
```
jsdoc'и пишутся минимум в три строчки

2024-05-06 10:33 UTC, cronon commented on src/utils/api/orderService/orderService.ts
> +    paymentStatus: string;
какие тут могут быть варианты? Я ожидал тоже увидеть здесь union string

2024-05-06 10:33 UTC, cronon commented on src/utils/api/orderService/orderService.ts
> +    /** Unique identifier for the client */
```suggestion
    /**
     * Unique identifier for the client who made the order.
     */
```
Когда мы смотрим на OrderState.userId важно понять какое отношение этот юзер имеет к этому заказу, и это отношение мы подчеркиваем в доках. Еще я бы сократил unique identifier до id, когда мы говорим об id это как бы по умолчанию подразумевается, что id уникальные у каждого объекта

2024-05-06 10:33 UTC, cronon commented on src/utils/api/orderService/orderServiceMock.ts
> +export const fetchOrderIdByClientId = async (userId: string): Promise<ApiResponse<string>> => {
Моковые функции тоже надо в класс поместить, такой же как и реальный сервис. Тогда можно будет просто в коде контекста легко поменять orderServiceMock на orderServiceReal и будет все работать как надо. 
Или так скажу, что когда мы делаем моки - то задача состоит в том, чтобы моки были максимально такой же формы, как и настоящий сервис.

Кстати, когда есть объекты одинаковой формы, но внутри них происходят разные действия, то это называется полиморфизмом.

2024-05-06 10:33 UTC, cronon commented on src/utils/api/orderService/orderServiceMock.ts
> +        return { data: null, error: 'No orders found for this client' };
Сообщения об ошибках должны проходить через i18n и показываться на юае.

2024-05-06 10:33 UTC, cronon commented on src/utils/api/orderService/orderSeviceReal.ts
> +                    : `Error ${response.status}`;
месседжи эти тоже должны проходить через i18n и показываться на юае. Список ошибок должен быть согласован, и тогда мы будем знать, что показывать юзеру для любой ситуации.

Лучше давай реальный сервис в отдельном тикете сделаем, чтобы этот ПР не тянуть. А сейчас пока удали реальный сервис

2024-05-06 10:33 UTC, cronon commented on src/pages/WaitingOrderPage/MockOrderList.ts
> +export const mockData: { orders: OrderState[] } = {
пусть это будет лежать рядом с моковым сервисом, т.к. оно юзается только там

2024-05-06 10:33 UTC, cronon commented on src/contexts/OrderContext.tsx
> +    setInitialPreparationTime: React.Dispatch<React.SetStateAction<number>>;
Эти сеттеры используются только внутри провайдера, и не используются в компонентах, поэтому не надо из экспротировать. Так же и остальные вещи, которые используются только здесь, не надо экспротировать наружу - так будет проще

2024-05-06 10:33 UTC, cronon commented on src/pages/PopupOrderCancelled/PopupOrderCancelled.tsx
> +                <img className={styles.popupOrderCancelled__image} src={waitingImg} alt="waiting image" />
должен быть background-image, проверь плз остальные места, чтобы там было так же

2024-05-06 10:33 UTC, cronon commented on src/utils/api/orderService/orderServiceMock.ts
> +
еще в моках должна быть какая-то возможность пройти полностью путь до готовности заказа, чтобы проверить что юай правильно работает. Сейчас я застрял на ожидании 
![image](https://github.com/bronfood-com/front/assets/4602009/b196f72a-4228-4426-882c-aadfd9cfd949)

2024-05-06 10:33 UTC, cronon commented on src/utils/hooks/useTimer/useTimer.ts
> + */
этот jsdoc должен быть прямо над функцией
```
 */
export function useTimers ...
```

2024-05-06 10:33 UTC, cronon commented on src/utils/hooks/useTimer/useTimer.ts
> +}
осталось непонятным что такое preparation time, wait time и cancellation countdown

2024-05-06 10:33 UTC, cronon commented on src/utils/hooks/useTimer/useTimer.ts
> + * Custom hook to manage and update various timers.
я так и не понял что делает этот хук
моя догадка: раз в секунду вызывает переданные функции с новыми значениями. Но значениями чего?

2024-05-06 10:33 UTC, cronon commented on src/utils/hooks/useTimer/useTimer.ts
> +                // Добавляем проверку на null
1. Комменты должны быть перед строчкой которую они поясняют или в конце ее
2. Все комменты должны быть на английском
3. То, что проверка на null, понятно собственно из кода. Но вот непонятно как может появиться ситуация, что это значение стало null. Вот это и надо пояснять в комментах - те вещи, которые непонятны только из кода

2024-05-09 19:49 UTC, mityourik commented on src/components/ProgressBar/ProgressBar.tsx
> +
убрал

2024-05-09 19:50 UTC, mityourik commented on src/components/ProgressBar/ProgressBar.tsx
> + * It calculates the progress percentage based on the initial total time and the current remaining time.
да. подправил в целом jsdoc

2024-05-09 21:16 UTC, mityourik commented on src/components/OrderTimeCounter/OrderTimeCounter.tsx
> +                        {t('components.orderTimeCounter.minutes')}
сделал пробел перед минутами

2024-05-09 21:34 UTC, mityourik commented on src/pages/WaitingOrderPage/WaitingOrder/WaitingOrder.tsx
> +    const WAIT_CODE_IN_SECONDS = 5 * 60; // секунды для ожидания кода заказа (запросить у бэка)
я хотел это время получать из какого-то отдельного запроса на наличие orderId. Сейчас я задал прогрессбару двигаться постоянно 2 минуты и опрашивать каждые 5сек пока в ответе не появится этот orderId

2024-05-09 21:37 UTC, mityourik commented on src/pages/WaitingOrderPage/WaitingOrder/WaitingOrder.tsx
> +    useEsc(() => setShowConfirmationPopup(false), [showConfirmationPopup]);
поправил

2024-05-09 21:50 UTC, mityourik commented on src/utils/api/orderService/orderService.ts
> +    id: string;
выполнено

2024-05-09 22:15 UTC, mityourik commented on src/utils/api/orderService/orderService.ts
> +    paymentStatus: string;
да. сделал paymentStatus: 'paid' | 'notPaid';

2024-05-09 22:19 UTC, mityourik commented on src/utils/api/orderService/orderService.ts
> +    /** Unique identifier for the client */
done

2024-05-10 12:12 UTC, mityourik commented on src/utils/api/orderService/orderServiceMock.ts
> +export const fetchOrderIdByClientId = async (userId: string): Promise<ApiResponse<string>> => {
поместил в класс

2024-05-10 12:47 UTC, mityourik commented on src/utils/api/orderService/orderServiceMock.ts
> +        return { data: null, error: 'No orders found for this client' };
исправил

2024-05-10 12:50 UTC, mityourik commented on src/utils/api/orderService/orderSeviceReal.ts
> +                    : `Error ${response.status}`;
я подправил реальный сервис, чтобы он в fetchResponse в зависимости от ключа ошибки обращался по ней к i18n. Может норм?))

2024-05-10 12:53 UTC, mityourik commented on src/pages/WaitingOrderPage/MockOrderList.ts
> +export const mockData: { orders: OrderState[] } = {
переместил

2024-05-10 21:20 UTC, mityourik commented on src/contexts/OrderContext.tsx
> +    setInitialPreparationTime: React.Dispatch<React.SetStateAction<number>>;
исправил

2024-05-10 21:53 UTC, mityourik commented on src/pages/PopupOrderCancelled/PopupOrderCancelled.tsx
> +                <img className={styles.popupOrderCancelled__image} src={waitingImg} alt="waiting image" />
исправил тут. В других местах у меня и в целом в проекте не нашел

2024-05-14 13:29 UTC, mityourik commented on src/utils/api/orderService/orderServiceMock.ts
> +
исправил этот мок чтобы он для тестировния UI устанавливал статусы для preparationStatus: 'waiting' | 'confirmed' | 'notConfirmed'. И в useOrderProvider добавил их, но пометил на удаление когда подставим реальные запросы.

2024-05-14 14:15 UTC, mityourik commented on src/utils/hooks/useTimer/useTimer.ts
> + */
пофикшено

2024-05-14 14:42 UTC, mityourik commented on src/utils/hooks/useTimer/useTimer.ts
> +}
дополнил jsdoc с объяснением этого)

2024-05-14 14:56 UTC, mityourik commented on src/utils/hooks/useTimer/useTimer.ts
> + * Custom hook to manage and update various timers.
в jsdoc-ах написал подробные объяснения

2024-05-14 15:04 UTC, mityourik commented on src/utils/hooks/useTimer/useTimer.ts
> +                // Добавляем проверку на null
в комменты включил объяснения что проверка на null необходима чтобы предотвратить ошибки в случае, если таймер был сброшен или очищен в другой части кода

2024-05-20 06:22 UTC, VladRyb commented on src/pages/WaitingOrderPage/WaitingOrder/WaitingOrder.tsx
> +                                        {formatTime(cancellationTime)} {t(getMinutesForm(cancellationTime))}
Задай еще фиксированную ширину для таймера, а то расстояние между цифрами и `мин.` постоянно прыгает

2024-05-20 06:27 UTC, VladRyb commented
И отвечу тут на вопрос про моки. Давай сделаем одинаковые в корзине и в заказе)

2024-05-27 16:14 UTC, VladRyb approved these changes

2024-05-28 09:10 UTC, merged