Feature/meal
bronfood-com/front pull request #76
Opened 2024-04-14 09:16 UTC by SergeyGetmanskiy

Экран Блюдо.
1. Верстка.
2. Логика нажатия на карточку блюда на экране Заведение. Если у блюда есть поле features тогда открывается экран Блюдо. Если нет, блюдо сразу попадает в Корзину.
3. Логика работы инпутов на экране Блюдо. Выбор опции автоматически меняет цену в графе Итого. Для этого задействован метод watch из useForm() react-hook-form.
4. Логика нажатия на кнопку добавить. Блюдо с выбранными добавками попадает в Корзину. При этом цена за единицу блюда, отображаемого в Корзине, равна сумме выбранного размера и добавок.
5. Изменения в моковый сервис Корзины. Чтобы правильно отображать блюда с размерами и добавками в Корзине. А именно, методу addMeal добавлен опциональный параметр features, а также изменения в логику работы с моковой базой данных.

2024-04-15 13:23 UTC, cronon requested changes

2024-04-15 15:13 UTC, SergeyGetmanskiy commented on src/App.tsx
1. починил.
2. починил. Почему то не работала связь по айдишнику между label и input. Убрал айдишник, сделал input дочерним у label и баг исчез.

2024-04-15 15:32 UTC, SergeyGetmanskiy commented on src/contexts/BasketContext.tsx
> +            return acc + current.count * current.meal.price;
починил

2024-04-15 15:39 UTC, SergeyGetmanskiy commented on src/pages/Basket/BasketMeal/BasketMeal.tsx
> +              const selectedChoice = current.choices.find((choice) => choice.default === true);
починил

2024-04-15 15:51 UTC, SergeyGetmanskiy commented on src/pages/Meal/Meal.tsx
> +    const restaurant: Restaurant | undefined = restaurantsFiltered.find((restaurant) => restaurant.id === params.restaurantId);
Так ведь на экран Блюдо можно попасть только из ресторана, на который, в свою очередь, зашел из списка отфильтрованных ресторанов. Если фильтры не установлены, то restaurantsFiltered === restaurantsOnMap (это правило у нас записано в контексте ресторанов). Вот я и подумал, что нет смысла искать во всех ресторанах, только в отфильтрованных.

2024-04-15 16:59 UTC, SergeyGetmanskiy commented on src/pages/Meal/Meal.tsx
> +                            return { ...choice, default: true };
Дело в том, что каждая feature имеет предустановленный choice (дефолтный). Тут я согласен, что поле с названием default не должно менять своё значение. Может default оставить, а добавить дополнительное chosen, куда будет записываться выбор пользователя?

2024-04-15 17:17 UTC, SergeyGetmanskiy commented on src/pages/Meal/Meal.tsx
> +function Meal() {
переименовал

2024-04-15 18:37 UTC, SergeyGetmanskiy commented on src/pages/Meal/MealFeatureList/MealFeatureList.tsx
> +    const isInView = useInView(choiceRef, {
До того, как дизайнер поменяла дизайн этого экрана, было так, что нижняя строка в списке добавок была гораздо бледнее остальных, вот я и применил useInView, чтобы когда строка частично скрыта за пределами блока, к ней бы применялся filter: opacity(20%).
Теперь в дизайне его нет. Но учитывая скорость, с которой меняется дизайн, завтра этот эффект может снова появиться)).

2024-04-15 18:40 UTC, SergeyGetmanskiy commented on src/pages/Restaurants/MockRestaurantsList.ts
> +                                price: 100,
сделал

2024-04-15 18:50 UTC, SergeyGetmanskiy commented on src/pages/Restaurants/MockRestaurantsList.ts
> +                ],
добавил

2024-04-15 18:57 UTC, SergeyGetmanskiy commented on src/utils/api/restaurantsService/restaurantsService.ts
> +    features?: Feature[];
поменял дефолтное значение на пустой массив

2024-04-15 20:32 UTC, SergeyGetmanskiy commented on src/utils/api/restaurantsService/restaurantsService.ts
> +    features?: Feature[];
> meal.price + sumBy(meal.features, f => f.choices.filter(c => c.chosen).map(c => c.price) )

я думаю так не получится, потому что у мила с фичой сложится meal.price + meal.features.choice['Размер'].price и в результате окажется удвоенная цена

2024-04-16 07:09 UTC, SergeyGetmanskiy commented on src/utils/api/basketService/basketServiceMock.ts
> +        const idPostfix =
Реакт будет ругаться, если при рендере списка блюд у них будут одинаковые айди. Я поэтому постфикс и применил, чтобы Реакт не ругался.

2024-04-16 09:50 UTC, SergeyGetmanskiy commented on src/pages/Meal/Meal.tsx
> +    if (meal && meal.features) {
Да, должна показываться страница 404. Но есть одна проблема. Пробую в валидном роуте, например, /restaurants/1/meal/1 слова на невалидные показывается экран 404, а если меняю цифры - то почему-то редиректит на /restaurants/ . Сейчас пытаюсь с этим разобраться, возможно придется использовать хук useRouteError из react-router.

2024-04-16 11:19 UTC, cronon commented on src/App.tsx
>Почему то не работала связь по айдишнику между label и input. Убрал айдишник, сделал input дочерним у label и баг исчез.

Вижу, это потому, что айди начиналось на цифру. Айди у элементов не может начинаться на цифру. Я делал обычно `id={'i'+feature.id}`. Сделать дочерним тоже подойдет, только если еслинт ругается, то все равно надо будет добавлять айди. И если добавлять айди, то надо, чтобы они были правильные. 

В общем, если сейчас все работает, то пускай работает

2024-04-16 11:27 UTC, cronon commented on src/pages/Meal/Meal.tsx
> +                            return { ...choice, default: true };
да, можно. Можно и по-другому как-нибудь. Но главное, чтобы две разные информации - дефолтный и выбранный чекбокс - в коде тоже были отдельно представлены

2024-04-16 11:41 UTC, cronon commented on src/pages/MealPage/MealPage.tsx
> +                        } else return { ...choice, default: false };
```suggestion
                        return { ...choice, default: choice.name === value[name]};
```

Когда происходят какие-то вычисления, и результатом их явно пишется return true или false, то я сразу подозреваю, именно строку с true или false можно опустить, а оставить только последнее вычисление

2024-04-16 11:41 UTC, cronon commented on src/pages/Meal/Meal.tsx
> +    const restaurant: Restaurant | undefined = restaurantsFiltered.find((restaurant) => restaurant.id === params.restaurantId);
>Если фильтры не установлены, то restaurantsFiltered === restaurantsOnMap

Эта вещь не очевидна когда читаешь только код MealPage не заглядывая больше в другие места. В таких ситуациях надо писать коммент, который поясняет почему так можно сделать. Но по возможности, таких умолчаний стоит избегать, а делать все максимально прямо. У нас такая возможность есть, так что нужно ей воспользоваться

Плюс на экран Блюдо можно попасть просто по ссылке

2024-04-16 11:46 UTC, cronon commented on src/pages/Meal/Meal.tsx
> +    if (meal && meal.features) {
подожди, useRouteError пока не для того

почему неправильные слова показывают 404 понятно - rrr/1/meal/1 - не матчится ни на один роут

почему происходит редирект - надо разбираться. По коду я думал, что должно так - роут допустим /restaurants/qqq/meal/www:

* из useParams приходят айди www и qqq, 
* MealPage функция возвращает undefined
* юзер видит пустой экран
 
Мб роутер так работает, что когда компонент выдает undefined, то он редиректит

2024-04-16 11:49 UTC, cronon commented on src/utils/api/restaurantsService/restaurantsService.ts
> +    features?: Feature[];
да, вижу
не, я больше имел в виду, что уберется if, а не что складывать цену мила с ценой его фич

2024-04-16 11:53 UTC, cronon commented on src/utils/api/basketService/basketServiceMock.ts
> +        const idPostfix =
а

если это только для рендера, то такие айди надо создавать там, где они рендерятся. Вообще, есть rule of thumb, что переменные объявляются максимально близко к своему первому использованию. Вот это что-то сродни - значения вычисляются как можно ближе к тому месту, где они нужны

2024-04-17 15:00 UTC, SergeyGetmanskiy commented on src/App.tsx
Оставил как есть (input вложен в label), потому что работает).

2024-04-17 15:06 UTC, SergeyGetmanskiy commented on src/pages/Meal/Meal.tsx
> +    const restaurant: Restaurant | undefined = restaurantsFiltered.find((restaurant) => restaurant.id === params.restaurantId);
Мысль понял. Починил. Теперь ищет среди всех ресторанов.

2024-04-18 06:41 UTC, SergeyGetmanskiy commented on src/pages/Meal/Meal.tsx
> +                            return { ...choice, default: true };
Добавил поле chosen. Но из-за этого пришлось переписать функцию вычисления price, аж в 3-х местах.

2024-04-22 09:17 UTC, SergeyGetmanskiy commented on src/pages/MealPage/MealPage.tsx
> +                        } else return { ...choice, default: false };
починил

2024-04-23 11:14 UTC, SergeyGetmanskiy commented on src/pages/Meal/Meal.tsx
> +    if (meal && meal.features) {
Разбираюсь с этим, но ещё не разобрался. 
Может создать отдельный тикет, чтобы это починить ?

2024-04-23 11:15 UTC, SergeyGetmanskiy commented on src/pages/Meal/MealFeatureList/MealFeatureList.tsx
> +    const isInView = useInView(choiceRef, {
В новом дизайне in-view эффекта нет, поэтому useInView убрал.

2024-04-23 12:09 UTC, SergeyGetmanskiy commented on src/App.tsx
Запросил согласие бэков на обновленную структуру данных для Meal, Feature, Choice.
https://www.notion.so/API-Restaurant-Meal-Basket-Order-e7947e0efa5948238032620646f28890

2024-04-23 13:41 UTC, cronon commented on src/pages/Meal/Meal.tsx
> +    if (meal && meal.features) {
да, давай

2024-04-23 13:43 UTC, cronon commented on src/utils/api/basketService/basketServiceMock.ts
> +        const idPostfix =
Вот это хорошй момент. Надо чтобы и реальный сервис тоже смог так сделать. Бэки знают, что к ним список фич будет приходить? Если знают, то хорошо, если не знают, то уведоми их и об этом тоже

2024-04-23 15:44 UTC, merged