Feature/restore password
bronfood-com/front pull request #79
Opened 2024-04-20 15:12 UTC by cipher24

Добавлена фича восстановления пароля, пока только с моковыми данными. 
Продолжаю заниматься реальными запросами.

тикет: https://github.com/orgs/bronfood-com/projects/1?pane=issue&itemId=48462224

2024-04-21 14:26 UTC, cipher24 commented
добавил реальные запрос, посмотреть работают ли в github pages.

2024-04-21 14:30 UTC, cipher24 commented
реальные запросы не работают. Локально работают. Вернул моковые запросы

2024-04-22 13:17 UTC, cronon requested changes

2024-04-22 13:17 UTC, cronon commented on src/utils/api/restorePasswordService/restorePasswordServiceMock.ts
> +        if (password === password_confirm) {
такая ситуация должна быть предотвращена уже на уровне компонента. На всякий случай не надо проверять, а надо чтобы код был максимально точно соответствовал нашему пониманию как все должно работать

2024-04-22 13:17 UTC, cronon commented on src/utils/api/restorePasswordService/restorePasswordServiceMock.ts
> +        if (temp_data_code && confirmation_code) {
такая ситуация должна быть предотвращена уже на уровне компонента. На всякий случай не надо проверять, а надо чтобы код был максимально точно соответствовал нашему пониманию как все должно работать

2024-04-22 13:17 UTC, cronon commented on src/utils/api/restorePasswordService/restorePasswordService.ts
> +};
респект за типы, у нас назревает нужда сделать такое же для остальных сервисов - но это потом

2024-04-23 09:49 UTC, cipher24 commented on src/components/SMSVerify/SMSVerify.tsx
> +const SMSVerify: FC<SMSVerify> = (props) => {
пробовал. Но там излишний интерфейс и его применение не вписывалось в моё решение. Переделывать его под себя - посчитал неправильным. Поэтому на его основе сделал для своей задачи версию попроще. Да как-то надо прийти к общему знаменателю. Посмотрю подробнее компонент SMSConfirm, что не устраивает меня и напишу Оле, она вроде с ним работала, и наверное нужно привести его к компромиссному виду?

2024-04-23 09:50 UTC, cipher24 commented on src/contexts/RestorePasswordContext.tsx
> +        localStorage.removeItem('confirmation_code');
чтобы работать с ними в разных местах. А как лучше сделать?

2024-04-23 09:52 UTC, cipher24 commented on .env
> +NODE_ENV = 'production'
наверное нужно удалить

2024-04-23 09:54 UTC, cipher24 commented on src/utils/api/restorePasswordService/restorePasswordService.ts
> +export type newPassword = {
окей. Исправлю

2024-04-23 09:55 UTC, cipher24 commented on src/utils/api/restorePasswordService/restorePasswordService.ts
> +     * user's phone number
окей, исправлю

2024-04-23 09:56 UTC, cipher24 commented on src/utils/api/restorePasswordService/restorePasswordServiceMock.ts
> +    }
ахаха, да. Уберу

2024-04-23 09:58 UTC, cipher24 commented on src/utils/api/restorePasswordService/restorePasswordServiceMock.ts
> +    generateTempDataCode(phoneNumber: string) {
согласен, не обдумывал это. Исправлю

2024-04-23 10:00 UTC, cipher24 commented on src/utils/api/restorePasswordService/restorePasswordServiceMock.ts
> +            return { status: 'error', error_message: 'something goes wrong' };
это же моковые запросы - вряд приложение в таком варианте дойдет до конечных пользователей?

2024-04-23 10:03 UTC, cipher24 commented on src/utils/api/restorePasswordService/restorePasswordServiceMock.ts
> +        if (password === password_confirm) {
да, хотел спросить. нужно ли на фронтовой стороне проверять совпадение пароля. Тут я больше написал такое условие, чтобы показать какую-то внутреннюю логику моковых запросов, а не просто чтобы они присылали ответ через 300мс.

2024-04-23 10:06 UTC, cipher24 commented on src/utils/api/restorePasswordService/restorePasswordService.ts
> +};
вроде без этого не работало

2024-04-23 11:16 UTC, cipher24 commented on src/components/Popups/Popup/Popup.module.scss
> +    padding: 50px 21px 55px;
с начала подумал все равно во всех попапах будет отступ по краям, но не учел, что может быть разный. 
Как будто тогда напрашивается отдельный компонент или элемент добавляющий отступы, чтобы не к чистому компоненты добавлять отступы. Переделаю

2024-04-23 11:17 UTC, cipher24 commented on src/pages/RestorePassword/RestorePassword.tsx
> +    const { isLoading, stage, queryPhone, requestChangePassword, applyPasswordChange } = useRestorePassword();
да, наверное, так будет правильнее

2024-04-23 14:24 UTC, cipher24 commented on src/utils/api/restorePasswordService/restorePasswordServiceMock.ts
> +        if (password === password_confirm) {
если убрать условие - тогда у нас моки всегда возвращают успешный ответ?

2024-04-25 13:01 UTC, cronon commented on src/utils/api/restorePasswordService/restorePasswordServiceMock.ts
> +            return { status: 'error', error_message: 'something goes wrong' };
не дойдет, но надо посмотреть, что "ошибки как в настоящем сервере" нормально проходят через i18n и показываются в юае

2024-04-25 13:03 UTC, cronon commented on src/utils/api/restorePasswordService/restorePasswordServiceMock.ts
> +        if (password === password_confirm) {
да
или моки могут вернуть ошибку такую же, как и реальный сервер

2024-04-29 10:06 UTC, cronon commented on src/pages/RestorePassword/RestorePassword.tsx
> +    } = useForm();
можно ли создавать useForm в каждом компоненте отдельно и не передавать его отсюда в компоненты? Если да, то надо так сделать. 
Чем меньше информации перемещается между компонентами, тем проще с ними работать, и вся система тоже становится проще

2024-04-29 10:06 UTC, cronon commented on src/pages/RestorePassword/RestorePassword.tsx
> +        if (tempDataCode !== '' && code !== '' && code.length === 4) {
этот момент надо обрабатывать в SMSVerify компоненте тоже

2024-04-29 10:06 UTC, cronon commented on src/utils/api/restorePasswordService/restorePasswordService.ts
> +export type newPassword = {
На будущее: отвечай на комменты когда они уже пофикшены в коде, так проще ревьювать и проще самому не забыть что еще надо сделать

2024-04-29 10:06 UTC, cronon commented on src/pages/RestorePassword/RestorePassword.tsx
> +    const { isLoading, stage, queryPhone, requestChangePassword, applyPasswordChange } = useRestorePassword();
Надо убрать контекст

2024-04-30 10:23 UTC, cipher24 commented on src/pages/RestorePassword/RestorePassword.tsx
> +    const { isLoading, stage, queryPhone, requestChangePassword, applyPasswordChange } = useRestorePassword();
my bad. код перенес, а файлы забыл удалить

2024-04-30 10:23 UTC, cipher24 commented on src/contexts/RestorePasswordContext.tsx
> +        localStorage.removeItem('confirmation_code');
my bad. код перенес, а файлы забыл удалить

2024-04-30 10:26 UTC, cipher24 commented on src/utils/api/restorePasswordService/restorePasswordService.ts
> +export type newPassword = {
А если не понятно что ты имеешь в виду или какой-то вопрос? 
Что исправить - отдельно выписываю себе по пунктам. По идее не должно теряться

2024-04-30 11:53 UTC, cipher24 commented on src/components/FormInputs/FormInputs.module.scss
> +    &__inputs {
согласен, моё нововведение выбивается из общей картины.
Но если мы хотим именовать по бэм разделение слов в имени блока или элемента одинарным нижним подчеркиванием - не подходит не к одной из схем. https://ru.bem.info/methodology/naming-convention/ мне кажется может возникнуть путаница из-за этого. Не хочется изобретать велосипеда и привыкать к нему. Может тогда разделять слова дефисами? по классической схеме бэм?

2024-04-30 12:00 UTC, cipher24 commented on src/components/SMSVerify/SMSVerify.module.scss
> +            &::-webkit-inner-spin-button {
скопировал из Олиного компонента, проверил, ничего не меняется без них - удалил

2024-04-30 12:06 UTC, cipher24 commented on src/components/SMSVerify/SMSVerify.tsx
> +    const valTest = ['[0-9]'];
ну какое-то общее впечатление. В жизни не уже не вспомню чтобы надо было вводить в мобильных приложениях не цифры. Я пропустил какую-то доку, где написано иное? Добавить буквы?

2024-04-30 12:51 UTC, cipher24 commented on src/i18n.tsx
> +
исправлю

2024-04-30 12:53 UTC, cipher24 commented on src/pages/RestorePassword/RestorePassword.tsx
> +            if (res.status === 'success') {
исправлю

2024-04-30 14:43 UTC, cipher24 commented on src/i18n.tsx
> +
исправлю

2024-04-30 14:43 UTC, cipher24 commented on src/pages/RestorePassword/RestorePassword.tsx
> +        if (mappedPhoneNumber !== '' && mappedPhoneNumber.length > 10) {
сделаю

2024-04-30 14:44 UTC, cipher24 commented on src/pages/RestorePassword/RestorePassword.tsx
> +            if (res.status === 'success') {
сделаю

2024-05-01 13:10 UTC, cronon commented on src/utils/api/restorePasswordService/restorePasswordService.ts
> +export type newPassword = {
> А если не понятно что ты имеешь в виду или какой-то вопрос?

Тогда спрашивай сразу

> Что исправить - отдельно выписываю себе по пунктам. По идее не должно теряться

Когда мой код ревьювают, то мне проще так делать и не выписывать отдельно

Когда я ревьюваю чужой код и вижу коммент "исправлено", то я понимаю что уже могу смотреть еще раз. Когда я вижу коммент "скоро исправлю" - то никакой информации мне это не дает, все равно нужно ждать отдельной отмашки от автора ПРа, что код можно ревьювать еще раз.

2024-05-01 13:18 UTC, cronon commented on src/components/FormInputs/FormInputs.module.scss
> +    &__inputs {
Мы используем css-модули и поэтому схемы именования не приведут к ошибкам. Наша схема именования классов не особо распространена, но какая сложилась, такая и сложилась: начинаются классы с маленькой буквы, слова разделяются подчеркиваниями. Можно делать бэм-стиль, можно не делать. - я добавлю этот момент в ридми

Если делать в одних файлах по одной схеме, а в других по другой, то они перемешаются и будет ничего непонятно. А чтобы приводить все к одной более распространенной схеме, то надо все переделывать, это потратится много времени.

2024-05-01 13:23 UTC, cronon commented on src/components/SMSVerify/SMSVerify.tsx
> +    const valTest = ['[0-9]'];
Такой доки я тоже не видел - и поэтому обратил внимание сюда. Моя интуиция говорит, что заказчик не будет против, если там будут только цифры, Тебе задача добавить этот момент, что "в смс приходят только цифры", в контракт и получить согласие от бэков.

2024-05-03 20:07 UTC, cipher24 commented on src/components/SMSVerify/SMSVerify.tsx
> +const SMSVerify: FC<SMSVerify> = (props) => {
В SMSConfirm компонент "успешная смена пароля" встроен внутрь. У меня это отдельный компонент и состояния page компонента. 
Так там оставалась ошибка которую мы разбирали на созвоне - подумал что будет неправильно переписывать Олин компонент на свой манер. Думаю, там еще какие-нибудь сложности совместимости возникли и это добавило работы. И так не могу сдать

2024-05-06 09:40 UTC, cronon commented on src/components/SMSVerify/SMSVerify.tsx
> +    const valTest = ['[0-9]'];
@cipher24 ты получил согласие от бэков?

2024-05-06 09:40 UTC, cronon commented on src/i18n.tsx
> +                            ValidationError: 'Введен некорректный номер телефона.',
здесь и далее: нужно начинать ключи с маленькой буквы

2024-05-06 09:40 UTC, cronon commented on src/components/InputPhone/InputPhone.tsx
> +    clearError?: () => void;
Судя по описанию, я передаю эту функцию внутрь инпута, а потом ее вызываю чтобы очистить инпут. Судя по коду - она вызывается на каждый onChange. 
Что-то здесь не так. Зачем ты используешь этот пропс?

2024-05-06 09:40 UTC, cronon commented on src/components/InputPhone/InputPhone.tsx
> +    clearError?: () => void;
Теперь я вижу, что этот пропс не используется. Надо его удалить отсюда и из остальных инпутов

2024-05-06 09:40 UTC, cronon commented on src/components/FormInputs/FormInputs.module.scss
> +    padding: 0 21px;
это глобальное изменение, которое затрагивает много вещей. Соответственно я ожидаю, что поменялись другие попапы, и чтобы они выглядели правильно после этих глобальных изменений, будут изменения и в других попапах.
Или ты можешь оставить здесь как есть, а паддинг добавить только в своих попапах

2024-05-06 09:40 UTC, cronon commented on src/utils/api/restorePasswordService/restorePasswordServiceMock.ts
> +            return { status: 'error', error_message: 'temp_data_code or confirmation_code is empty' };
как эта ошибка отображается на юае?
Можно сделать условие типа `if(confirmation_code==='4444') { return error }` Тогда можно будет протестировать как ошибка на юае показывается

2024-05-06 12:08 UTC, cipher24 commented on src/utils/api/restorePasswordService/restorePasswordServiceMock.ts
> +            return { status: 'error', error_message: 'temp_data_code or confirmation_code is empty' };
отличная идея! добавил

2024-05-06 12:08 UTC, cipher24 commented on src/components/FormInputs/FormInputs.module.scss
> +    padding: 0 21px;
ок

2024-05-06 12:09 UTC, cipher24 commented on src/i18n.tsx
> +                            ValidationError: 'Введен некорректный номер телефона.',
ок

2024-05-06 12:12 UTC, cipher24 commented on src/components/InputPhone/InputPhone.tsx
> +    clearError?: () => void;
используется, чтобы стирать текст ошибки. Если например ввести несуществующий номер (744444444444 для моков) то без этого пропа ошибка перейдет на следующий экран. Уверен можно как-то сделать элегантнее - но сам пока такое решение не нашел, чтобы работало.

2024-05-06 13:16 UTC, cronon commented on src/components/InputPhone/InputPhone.tsx
> +    clearError?: () => void;
Тогда так и делай setIsError(false) когда переходишь на следующий экран. Например
```
const onSubmitQueryPhone = async (phoneNumber: string) => {
        setIsLoading(true);
        const res = await restorePasswordService.queryPhoneNumber(phoneNumber);
        if (res.status === 'success') {
          setIsError(false)
```

2024-05-06 17:54 UTC, cipher24 commented on src/components/InputPhone/InputPhone.tsx
> +    clearError?: () => void;
сделал. Но хотелось сделать именно "пользователь увидел ошибку ->начинает вводить скорректированные данные = значит ошибка больше не нужна, можно очистить"

2024-05-07 12:36 UTC, cronon commented on src/components/InputPhone/InputPhone.tsx
> +    clearError?: () => void;
Понятно, такая логика полностью принадлежит компоненту RestorePassword, в котором изменяется стейт isError. 
 То есть RestorePassword решает, показывать ошибку или нет.

А инпут не принимает такого решения, инпут может только дать сигнал, что пользователь начинает вводить заново. Соответственно, и пропс у него должен быть не clearError, а onChange если колбэк вызывается на каждый чендж, как было у тебя. Или можно сделать пропс onFirstChange, и тогда в самом инпуте отслеживать первый это чендж или второй.

Какую логику нам выбрать: как была изначально или как стала теперь? Как лучше будет юзерам и нам? 

Мне хочется замержить быстрее ПР и оставить все как есть. Еще я вижу что react-use-form-hook не убирает ошибку как только ты начал писать что-то новое. Например, я написал при входе пароль русскими буквами и он показал мне, что так нельзя. Я начал писать пароль английскими, и ошибка не исчезла до тех пор пока я не нажал сабмит еще раз. Пускай и здесь будет так же. Мб это не 100% удобно для юзеров, но то, что так сделано в модной библиотеке говорит о том, что такое поведение все-таки распространено и не становится для юзеров катастрофой, что они аж не знают что делать.

2024-05-07 12:36 UTC, cronon approved these changes

2024-05-07 13:21 UTC, merged