Feature/use esc hook
bronfood-com/front pull request #83
Opened 2024-04-28 18:52 UTC by SergeyGetmanskiy

Кастомный хук для закрытия попапов по клавише 'Esc'

У хука 2 параметра: 
1. Фукция, которая выполняется при нажатии на 'Esc'
2. Флаг, который сообщает о том, есть ли перед попапом другой попап, который также может быть закрыт по 'Esc' . Если флаг = true, то попап, который вызвал хук, не закроется. Пример: попап подтверждения очистки Корзины, который появляется перед попапом Корзины.

2024-04-29 10:38 UTC, cronon requested changes

2024-04-29 10:38 UTC, cronon commented on src/pages/Basket/BasketPopup/BasketPopup.tsx
> +    useEsc(close, isConfirmationPopupOpen);
Тяжело внятно объяснить что делает этот флаг в useEsc, соответственно с ним будут потом проблемы
Логику с  isConfirmationPopupOpen лучше оставить здесь, а не внутри useEsc: `useEsc( useCallback(() => !isConfirmationPopupOpen && close(), [isConfirmationPopupOpen, close])  )`.

2024-04-29 10:38 UTC, cronon commented on src/utils/hooks/useEsc/useEsc.tsx
> +export const useEsc = (handleFunction: () => void, isForegroundPopupOpen: boolean = false) => {
Добавь пожалуйста jsdoc к хуку

2024-04-29 10:38 UTC, cronon commented on src/pages/Basket/BasketPopup/BasketPopup.tsx
>      return (
Кстати, я открыл ресторан, нажал на Esc, попап с ресторанами спрятался, показывается список ресторанов. Я открыл ресторан опять, нажал на куриный донер, открылся попап с фичами. Нажал на Esc, попап с фичами закрылся. Ожидание: будет виден попап с рестораном. Происходит: попапа с рестораном нет, показывается список ресторанов.

2024-04-29 10:38 UTC, cronon commented on src/utils/hooks/useEsc/useEsc.tsx
> +    });
я задумался, не нужно ли сюда в зависимостях передавать handleFunction? С одной стороны если она сохранится в замыкании, то нужно ее обновлять. С другой стороны - вроде не должна, а должна браться по ссылке.
Придумай плз и проведи эксперимент, чтобы это выяснить. Если действительно не надо передавать ее в зависимостях, то напиши здесь в комменте потому, что это будет неожиданный момент

2024-04-29 11:20 UTC, SergeyGetmanskiy commented on src/pages/Basket/BasketPopup/BasketPopup.tsx
> +    useEsc(close, isConfirmationPopupOpen);
починил

2024-04-29 11:50 UTC, SergeyGetmanskiy commented on src/utils/hooks/useEsc/useEsc.tsx
> +export const useEsc = (handleFunction: () => void, isForegroundPopupOpen: boolean = false) => {
добавил

2024-04-29 12:02 UTC, SergeyGetmanskiy commented on src/pages/Basket/BasketPopup/BasketPopup.tsx
>      return (
Я полностью с тобой согласен, что попап с рестораном должен остаться.
Но, когда я спрашивал заказчика про кнопку "Назад" вот здесь https://www.figma.com/file/9H7H1cGkW9CYB7iFRpm7x3?type=design&node-id=647-7603&mode=design#766655601 он заодно прокомментировал кнопку "Крестик", что она должна возвращать аж на карту. Ну спорить с заказчиком я не стал. Ему виднее, наверное)
А так как, клик по "Esc" то же самое, что клик по "Крестику" , то "Esc" возвращает на список ресторанов.
Может ещё раз уточнить этот момент у заказчика?

2024-04-29 12:37 UTC, SergeyGetmanskiy commented on src/utils/hooks/useEsc/useEsc.tsx
> +    });
Эксперимент провёл. И вот что выяснилось:
1. С точки зрения UX все 3 варианта (без массива зависимостей, с handleFunction в зависимостях, c пустым массивом зависимостей) приводят к одинаковому поведению: попапы закрываются по 'Esc'.
2. Но eslint всё таки рекоммендует сделать вот так: 
![image](https://github.com/bronfood-com/front/assets/122983365/c3c1a9f8-5bf6-45d2-ab1d-61951231cfd0)
3. Здесь также предлагают функцию обернуть  в useCallback, и передать её в массив зависимостей эффекта. https://stackoverflow.com/a/59963095

2024-04-29 14:28 UTC, cronon commented on src/pages/Basket/BasketPopup/BasketPopup.tsx
>      return (
а, а как по мне, Esc скорее отменяет самое последнее действие. Что-то выскочило - нажал Esc - оно ушло

2024-04-29 14:36 UTC, cronon commented on src/utils/hooks/useEsc/useEsc.tsx
> +    });
Эксперимент я имею в виду посмотреть как оно действительно будет работать. Если я на первый рендер передаю в useEsc одну функцию, а на второй - вторую, то какие функции потом будут вызываться в случае, когда в useEffect указаны зависимости, и в случае когда не указаны

И тоже самое надо проверить с useCallback, не круто если его нужно будет писать каждый раз перед useEsc. Мб useCallback совсем можно опустить или заюзать внутри useEsc?

Ну внутри точно нельзя, useEsc нужно тогда будет как-то узнать зависимости

О, а вот как вариант передавать зависимости в useEsc `useEsc(() => !isConfirmOpen && close(), [isConfirmOpen])`

2024-04-29 18:30 UTC, SergeyGetmanskiy commented on src/pages/Basket/BasketPopup/BasketPopup.tsx
>      return (
ну да, действительно, ведь "Esc" всё таки немного отличается от "Крестика" по смыслу. Тогда можно у заказчика не спрашивать. 
Вообщем сделал, чтобы просто закрывался попап с фичами.

2024-04-29 20:19 UTC, SergeyGetmanskiy commented on src/utils/hooks/useEsc/useEsc.tsx
> +    });
> О, а вот как вариант передавать зависимости в useEsc `useEsc(() => !isConfirmOpen && close(), [isConfirmOpen])`

Не знал, что кастомному хуку тоже можно передавать массив зависимостей. 
Сделал так для RestaurantPopup и BasketPopup

2024-04-29 20:27 UTC, SergeyGetmanskiy commented on src/utils/hooks/useEsc/useEsc.tsx
> +    });
> то какие функции потом будут вызываться в случае, когда в useEffect указаны зависимости, и в случае когда не указаны

В обоих случаях вызываются те функции, которые передаются. Как будто зависимости в эффекте ни на что не влияют.

2024-04-30 12:10 UTC, cronon commented on src/utils/hooks/useEsc/useEsc.tsx
> +    });
>То есть, передавать в useEsc 2 параметра? Функцию и массив зависимостей? А как это потом в эффекте использовать?

типа так useEsc(() => !isConfirmOpen && close(), [isConfirmOpen, close])

function useEsc(cb, deps){
 const handler = useCallback(cb, deps)
  useEffect(() => ... , handler)
}

чтобы не писать useCallback каждый раз 

или что ты имеешь в виду в этом вопросе?

2024-05-02 15:13 UTC, cronon approved these changes

2024-05-02 16:52 UTC, merged