added pages feedback and about-us
bronfood-com/front pull request #86
Opened 2024-05-07 11:55 UTC by cipher24

тикет: https://github.com/orgs/bronfood-com/projects/1?pane=issue&itemId=60861750
Добавлены страницы "О нас" и "О сервисе"

2024-05-07 13:11 UTC, cronon requested changes

2024-05-07 13:11 UTC, cronon commented on src/pages/Feedback/FeedbackPopup/FeedbackPopup.tsx
> +                </Form>
button должен быть type="submit"

2024-05-07 13:11 UTC, cronon commented on src/pages/Feedback/FeedbackPopup/FeedbackPopup.tsx
> +                <Form className={styles.feedback_popup__form} control={control}>
Нужно делать новый контракт с бэком, чтобы эта форма появилась в мастере уже полностью рабочая. Просто так если оставить неработающие фичи, то они остаются навечно висеть в воздухе и смущать юзеров.

На сейчас лучше удали эту форму, тогда можно будет смержить ПР. И сделай отдельный тикет, чтобы добавить эту форму вместе с бэком.

2024-05-07 20:14 UTC, cipher24 commented on src/components/AboutUs/AboutUs.module.scss
> +.AboutUs {
ок

2024-05-07 20:14 UTC, cipher24 commented on src/components/AboutUs/AboutUs.tsx
> +                <div className={styles.AboutUs__main}>Бронфуд - это маркетплейс для заказ еды на вынос. Больше не нужно ждать, когда приготовят ваш заказ. Оплачивайте и приходите, когда уже всё готов
исправил. оставил коммент

2024-05-07 20:16 UTC, cipher24 commented on src/i18n.tsx
> +                            button: 'Отправить',
Исправил. Ориентировался по другим ключам, например "title"ов много.

2024-05-07 20:16 UTC, cipher24 commented on src/pages/Feedback/Feedback.tsx
> +    // const navigate = useNavigate();
согласен

2024-05-07 20:17 UTC, cipher24 commented on src/pages/Feedback/FeedbackPopup/FeedbackPopup.tsx
> +                    <div>{t('pages.feedback.privacyPolicy')}</div>
удалил. тикет создал

2024-05-07 20:17 UTC, cipher24 commented on src/pages/Feedback/FeedbackPopup/FeedbackPopup.tsx
> +                </Form>
ок

2024-05-07 20:20 UTC, cipher24 commented on src/pages/Feedback/FeedbackPopup/FeedbackPopup.tsx
> +                    <textarea className={styles.feedback_popup__textarea} name="input" placeholder={t('pages.feedback.placeholder')} autoComplete="off" minLength={5} required wrap="soft" />
про minLength лишнее наверное. А wrap="soft" - это чтобы отправлялась текст одной строкой. Почему-то показалось, что нет причин отправлять иначе. Ну ок - убрал

2024-05-07 20:20 UTC, cipher24 commented on src/pages/Feedback/FeedbackPopup/FeedbackPopup.tsx
> +                <Form className={styles.feedback_popup__form} control={control}>
форму убрал. тикет сделал

2024-05-07 20:21 UTC, cipher24 commented on src/components/Popups/Popup/Popup.tsx
> +        navigate(-1);
да, так будет логичнее. Сделал

2024-05-07 20:21 UTC, cipher24 commented on src/components/Popups/Popup/Popup.tsx
> +        navigate(-1);
да, так будет логичнее. Сделал

2024-05-07 20:21 UTC, cipher24 commented on src/components/Popups/Popup/Popup.module.scss
> +    }
ок

2024-05-08 13:43 UTC, cronon commented on src/i18n.tsx
> +                            maxLengthErrorMessage: 'Максимальное количество символом - ',
```suggestion
                            maxLengthErrorMessage: 'Максимальное количество символов - ',
```

2024-05-08 13:44 UTC, cronon approved these changes

2024-05-08 13:55 UTC, merged